anvil-verifier/anvil

- src/kubernetes_cluster/spec/client.rs
- src/kubernetes_cluster/spec/common.rs
- src/kubernetes_cluster/spec/controller/common.rs
- src/kubernetes_cluster/spec/controller/controller_runtime.rs
- src/simple_controller/proof/liveness.rs
- src/simple_controller/proof/safety.rs
- src/temporal_logic/rules.rs
Enhance the liveness property of the simple controller by adding stability. That is, existence of the CR leads to existence of the configmap, and the configmap always exists from then.
> Simple controller: prove stability

- src/kubernetes_cluster/proof/kubernetes_api_liveness.rs
- src/simple_controller/proof/liveness.rs
- src/simple_controller/spec/simple_reconciler.rs
- src/temporal_logic/rules.rs
This PR does the following:
- Prove all the lemmas used by simple controller liveness proof
- Simplify some lemmas using a new lemma tla_forall_always_equality_variant
- Simplify some lemmas using a new lemma execution_equality, which replaces the old execution_merge/split lemmas
> Cosmetic changes before complicating simple controller spec

- src/kubernetes_cluster/proof/controller_runtime_liveness.rs
- src/kubernetes_cluster/proof/kubernetes_api_liveness.rs
- src/kubernetes_cluster/proof/kubernetes_api_safety.rs
- src/kubernetes_cluster/proof/wf1_assistant.rs
- src/kubernetes_cluster/spec/controller/common.rs
- src/kubernetes_cluster/spec/controller/controller_runtime.rs
- src/kubernetes_cluster/spec/controller/state_machine.rs
- src/kubernetes_cluster/spec/distributed_system.rs
- src/kubernetes_cluster/spec/reconciler.rs
- src/simple_controller/proof/liveness.rs
- src/simple_controller/proof/safety.rs
- src/simple_controller/spec/simple_reconciler.rs
ReconcileState was used to describe the local state of each Reconcile round and was previously a hardcoded type.
This PR makes it a generic type called T.
Signed-off-by: Xudong Sun <xudongs1@vmware.com>
> Make ReconcileState a generic type RS

- src/kubernetes_cluster/proof/controller_runtime_liveness.rs
- src/kubernetes_cluster/proof/kubernetes_api_liveness.rs
- src/kubernetes_cluster/spec/client.rs
- src/kubernetes_cluster/spec/common.rs
- src/kubernetes_cluster/spec/controller/common.rs
- src/kubernetes_cluster/spec/controller/controller_runtime.rs
- src/kubernetes_cluster/spec/controller/state_machine.rs
- src/kubernetes_cluster/spec/kubernetes_api/builtin_controllers/statefulset_controller.rs
- src/kubernetes_cluster/spec/kubernetes_api/common.rs
- src/kubernetes_cluster/spec/kubernetes_api/state_machine.rs
- src/kubernetes_cluster/spec/reconciler.rs
- src/simple_controller/proof/liveness.rs
- src/simple_controller/proof/mod.rs
- src/simple_controller/proof/safety.rs
- src/simple_controller/proof/shared.rs
- src/simple_controller/spec/simple_reconciler.rs
- src/temporal_logic/rules.rs
To match the response (from the k8s API) and the request (sent to the k8s API), this PR adds a req_id to each request and the k8s API state machine will attach the same id to the response after handling each request. This req_id only applies to <request, response> pairs, and watch event messages do not have any such id.
The req_id has to be unique to differentiate responses for different requests. The controller, k8s API and client state machine maintains a req_id variable respectively which always increments after sending out one request. An alternative is to let the top-level k8s cluster state machine maintain the req_id and pass it to each individual state machine, but that requires the k8s cluster state machine to know how many requests each individual state machine sends out in each …
> Add unique id to request/response pair

- src/kubernetes_cluster/proof/controller_runtime_liveness.rs
- src/kubernetes_cluster/proof/kubernetes_api_liveness.rs
- src/kubernetes_cluster/proof/wf1_assistant.rs
- src/kubernetes_cluster/spec/client.rs
- src/kubernetes_cluster/spec/common.rs
- src/kubernetes_cluster/spec/controller/controller_runtime.rs
- src/kubernetes_cluster/spec/controller/state_machine.rs
- src/kubernetes_cluster/spec/distributed_system.rs
- src/kubernetes_cluster/spec/kubernetes_api/state_machine.rs
- src/kubernetes_cluster/spec/network.rs
- src/pervasive_lemmas/seq_lemmas.rs
- src/simple_controller/proof/liveness.rs
- src/simple_controller/proof/safety.rs
- src/simple_controller/proof/shared.rs
- src/simple_controller/spec/simple_reconciler.rs
- src/state_machine/action.rs
- src/temporal_logic/rules.rs
- src/tla_examples/abc/liveness.rs
- src/tla_examples/abc/state_machine.rs
- src/tla_examples/compound/controller.rs
- src/tla_examples/compound/distributed_system.rs
- src/tla_examples/compound/kubernetes_api.rs
- src/tla_examples/compound/network.rs
- src/tla_examples/concurrent/liveness.rs
- src/tla_examples/concurrent/state_machine.rs
- src/tla_examples/sequential/state_machine.rs
Since Verus supports ghost `==` https://github.com/verus-lang/verus/pull/352, we can stop using `===` and start to use `==` in spec and proof code. This PR simply replaces all the `===` with `==` and adds a few type annotations as Verus requires.
> Use `==` for spec eq

- src/kubernetes_cluster/proof/controller_runtime_liveness.rs
- src/kubernetes_cluster/proof/wf1_assistant.rs
- src/kubernetes_cluster/spec/common.rs
- src/kubernetes_cluster/spec/controller/common.rs
- src/kubernetes_cluster/spec/controller/controller_runtime.rs
- src/kubernetes_cluster/spec/controller/state_machine.rs
- src/kubernetes_cluster/spec/kubernetes_api/state_machine.rs
- src/main.rs
Specify the controller's list-then-watch pattern.
Controllers use the list-then-watch pattern to observe the cluster state: it first issues a list to read the current cluster state, and the list returns a resource version indicating the "version" of the cluster state the controller just reads. Every single update to any object in the cluster state will increment the resource version number. After the list returns, the controller issues a watch request to continuously receive updates to the cluster state. When issuing the watch request, the controller specifies the resource version number returned by the list, which asks the apiserver to stream updates starting from the resource version.
The current specification is much more simplified than the above: since we have not specified resource …
> Specify the controller's list-then-watch pattern

- src/temporal_logic/defs.rs
- src/temporal_logic/rules.rs
Implement a lemma `unpack_assumption_from_spec` to conveniently unpack assumption from the spec.
This will simplify our liveness proof later: we will pack the assumption into the spec and drop init, and use the new spec `partial_spec /\ assumption` through the liveness proof. For any safety invariant we will need during the liveness proof, we will merge them into `partial_spec`. The liveness proof will try to prove `partial_spec /\ assumption |= True ~> p`. We will also need to prove `spec |= init /\ partial_spec`. Finally, by applying this lemma we will get `init /\ partial_spec |= assumption ~> []match(cr)`, and conclude `spec |= assumption ~> []match(cr)`. Here `assumption` is `[]exists(cr)`.
> Prove lemmas to unpack assumption

- src/kubernetes_api_objects/common.rs
- src/kubernetes_api_objects/config_map.rs
- src/kubernetes_api_objects/custom_resource.rs
- src/kubernetes_api_objects/mod.rs
- src/kubernetes_api_objects/object.rs
- src/kubernetes_api_objects/persistent_volume_claim.rs
- src/kubernetes_api_objects/pod.rs
- src/kubernetes_api_objects/service.rs
- src/kubernetes_cluster/proof/controller_runtime_liveness.rs
- src/kubernetes_cluster/proof/controller_runtime_safety.rs
- src/kubernetes_cluster/proof/kubernetes_api_liveness.rs
- src/kubernetes_cluster/proof/kubernetes_api_safety.rs
- src/kubernetes_cluster/spec/client.rs
- src/kubernetes_cluster/spec/common.rs
- src/kubernetes_cluster/spec/controller/common.rs
- src/kubernetes_cluster/spec/controller/controller_runtime.rs
- src/kubernetes_cluster/spec/distributed_system.rs
- src/kubernetes_cluster/spec/kubernetes_api/builtin_controllers/statefulset_controller.rs
- src/kubernetes_cluster/spec/kubernetes_api/common.rs
- src/kubernetes_cluster/spec/kubernetes_api/state_machine.rs
- src/kubernetes_cluster/spec/reconciler.rs
Replace all the toy k8s object definitions with the newly implemented k8s openapi objects in spec and proof.
> Use k8s openapi objects in spec and proof

- src/kubernetes_cluster/proof/controller_runtime_liveness.rs
- src/kubernetes_cluster/proof/controller_runtime_safety.rs
- src/kubernetes_cluster/proof/kubernetes_api_safety.rs
- src/kubernetes_cluster/proof/wf1_assistant.rs
- src/kubernetes_cluster/spec/controller/common.rs
- src/kubernetes_cluster/spec/controller/controller_runtime.rs
- src/kubernetes_cluster/spec/controller/state_machine.rs
- src/kubernetes_cluster/spec/distributed_system.rs
- src/kubernetes_cluster/spec/kubernetes_api/state_machine.rs
Add an action that checks if a cr exists in the Kubernetes API and, if so, inserts a reconcile request for that cr to the controller and assumes weak fairness on this action.
This allows us to set up the assumption that reconcile is infinitely frequently scheduled without modeling all the details about list-then-watch and resource versions.
Some of the existing lemmas for proving `p ~> reconcile_triggered` become deprecated and we will need to write new lemmas by packing the assumption into the spec and prove `true ~> reconcile_triggered`.
> Assume the controller's reconcile is infinitely frequently triggered

- src/kubernetes_cluster/proof/controller_runtime_liveness.rs
- src/kubernetes_cluster/spec/distributed_system.rs
Prove `[]next /\ []fair /\ []cr_exists |= true ~> reconcile_scheduled_for_cr`. This is way simpler than the previous reasoning about watch events and it will be the starting point of our liveness proof.
> Prove true leads to reconcile scheduled under the assumption that cr always exists

- src/simple_controller/proof/liveness.rs
Prove the lemma `simple_controller::proof::liveness::lemma_after_create_cm_pc_leads_to_cm_always_exists`. This lemma ensures that after a custom resource is added to the ongoing reconciles of the controller, it will eventually appear and always exists in the resources of k8s api.
> Fix simple controller liveness proof: Prove `after_create_cm_pc ~> cm_always_exists`

- src/kubernetes_cluster/proof/cluster.rs
- src/kubernetes_cluster/proof/mod.rs
- src/kubernetes_cluster/spec/distributed_system.rs
- src/simple_controller/proof/liveness.rs
- src/temporal_logic/rules.rs
Assume that `spec |= reconcile_ongoing ~> []cr_matched`, I complete the liveness proof. If we want to make `spec |= reconcile_ongoing ~> []cr_matched` verified as well, we have to prove `spec |= reconcile_error ~> []cr_matched`, since the other three cases (`init`, `get_cr`, `create_cm`) have all been proved. But considering it may not be possible to prove `spec |= reconcile_error ~> []cr_matched` under current specifications, another proof strategy is needed.
> Prove simple controller liveness except the reconcile error case

- src/kubernetes_cluster/proof/controller_runtime_safety.rs
- src/kubernetes_cluster/spec/channel.rs
- src/kubernetes_cluster/spec/client.rs
- src/kubernetes_cluster/spec/controller/common.rs
- src/kubernetes_cluster/spec/controller/controller_runtime.rs
- src/kubernetes_cluster/spec/controller/state_machine.rs
- src/kubernetes_cluster/spec/kubernetes_api/builtin_controllers/statefulset_controller.rs
- src/kubernetes_cluster/spec/kubernetes_api/common.rs
- src/kubernetes_cluster/spec/kubernetes_api/state_machine.rs
- src/kubernetes_cluster/spec/mod.rs
- src/simple_controller/proof/safety.rs
Use ChannelManager to wrap around the channel id. ChannelManager is part of the host state machine and allocates a new channel id when sending a new request.
Ideally, the concept of channel should be modeled in the network state machine, but I found that will complicate the spec a lot. For example, we will need to differentiate whether the host is sending to an existing channel or sending to a new channel, and when a new channel is created in the network, the host somehow needs to know the channel id and waits for the message sent back to that channel. We will need to revisit the design of network state machine later.
> Add channel manager to allocate channel id for each controller request

- src/kubernetes_cluster/proof/controller_runtime_liveness.rs
- src/kubernetes_cluster/proof/controller_runtime_safety.rs
- src/kubernetes_cluster/proof/kubernetes_api_liveness.rs
- src/simple_controller/proof/liveness.rs
- src/simple_controller/proof/safety.rs
- src/simple_controller/spec/simple_reconciler.rs
- src/temporal_logic/rules.rs
The liveness property of simple controller is verified with all possible cases considered. To achieve this, I also parameterize the `spec` in proof of Kubernetes API so that we can specify whether `sm_spec` or `sm_partial_spec` is required. Plus, some rules are added to `temporal_logic::rules`.
Explanatory comments need to be supplemented.
> Complete simple controller liveness proof

- src/kubernetes_cluster/proof/cluster.rs
- src/kubernetes_cluster/proof/mod.rs
- src/kubernetes_cluster/proof/wf1_assistant.rs
- src/kubernetes_cluster/spec/controller/common.rs
- src/kubernetes_cluster/spec/controller/state_machine.rs
- src/kubernetes_cluster/spec/distributed_system.rs
- src/simple_controller/mod.rs
- src/temporal_logic/rules.rs
Specify controller crash and add weak fairness assumption to express "the controller eventually stops crashing".
To support specifying crash, we place controller_state in an Option and use Option::None to represent the case where the controller is not running, and we add a crash_enabled bit as the precondition to crash the controller. We add three new actions to the top-level state machine:
- crash_controller that sets the controller state to Option::None and if crash_enabled
- restart_controller that restarts the controller with the initial controller state if the controller is not running
- disable_crash that sets crash_enabled to false
We also add weak fairness assumption on restart_controller and disable_crash so that later we can prove eventually the controller stops crashing and is …
> Specify controller crash behavior

- src/kubernetes_cluster/proof/cluster.rs
- src/kubernetes_cluster/proof/wf1_assistant.rs
- src/kubernetes_cluster/spec/distributed_system.rs
Collapse the previous `crash_controller` and `restart_controller` into one action. This would simplify the proof because we no longer need to carry the Option. Note that the new specification on crash still allows the execution that the controller restart does not immediately happen after the crash: not scheduling any controller action before `restart_controller` is the same as the controller is crashed and then restarted by `restart_controller`.
> Make crash and restart atomic

- src/kubernetes_cluster/proof/cluster.rs
- src/kubernetes_cluster/proof/controller_runtime_liveness.rs
- src/kubernetes_cluster/proof/mod.rs
- src/kubernetes_cluster/spec/distributed_system.rs
- src/simple_controller/mod.rs
- src/simple_controller/proof/liveness.rs
- src/temporal_logic/rules.rs
When crash is enabled, we can first assume that the system enters a state $S$ when crash will always be disabled and cm always exists will eventually happen. The rest is to prove that under our spec, state $S$ will be reached anyway.
This means to separate the verification into two parts:
(1) `spec |= []cr_exists ~> []cr_exists /\ [] !crash_enabled`
(2) `spec |= []cr_exists /\ [] !crash_enabled ~> []cr_matched`
The second is similar to the previous proof.
> Prove simple controller liveness under crash

- src/kubernetes_api_objects/api_method.rs
- src/kubernetes_api_objects/error.rs
- src/kubernetes_api_objects/mod.rs
- src/kubernetes_cluster/proof/kubernetes_api_liveness.rs
- src/kubernetes_cluster/spec/kubernetes_api/state_machine.rs
- src/kubernetes_cluster/spec/message.rs
Bridge APIError, which is used in spec and proof, and kube::Error, which is used in implementation code.
> Model kube::Error as APIError

- src/kubernetes_api_objects/api_method.rs
- src/kubernetes_api_objects/object.rs
- src/simple_controller/exec/reconciler.rs
- src/simple_controller/proof/mod.rs
- src/simple_controller/spec/simple_reconciler.rs
This PR makes the simple controller decide the next reconciliation step by checking the response to the previous request. The liveness proof needs to be fixed using the strategy in #77 .
Some of the helper functions can be merged into vstd::result.
> Make simple controller aware of response

- .github/workflows/regression-testing.yml
Avoid using actions-rs/toolchain@v1 which is not allowed by the current GitHub workflow setting. And enable actions for push and pull requests as well.
> Avoid using unofficial workflow actions

- src/controller_examples/simple_controller/proof/liveness.rs
- src/kubernetes_cluster/proof/cluster.rs
- src/kubernetes_cluster/proof/controller_runtime_liveness.rs
- src/kubernetes_cluster/proof/controller_runtime_safety.rs
- src/simple_controller.rs
- src/temporal_logic/rules.rs
This is to address the issue that we have to keep adding proof functions that take different numbers of arguments for different use cases. This PR adds macros for certain TLA rules that take an arbitrary number of arguments.
> Generate TLA proofs with any number of arguments using macros

- src/kubernetes_cluster/proof/controller_runtime_safety.rs
Shorten the lemma `lemma_always_every_in_flight_msg_has_lower_id_than_chan_manager` by moving the proof inside `assert forall` in another proof function. In this case, we will not get a warning `function body check has been running for 2 seconds` every time.
> Shorten verification time by rewriting controller runtime safety lemma

- build.sh
- src/controller_examples/simple_controller/spec/custom_resource.rs
- src/controller_examples/zookeeper_controller/exec/reconciler.rs
- src/controller_examples/zookeeper_controller/spec/zookeepercluster.rs
- src/deps_hack/src/lib.rs
- src/kubernetes_api_objects/api_resource.rs
- src/kubernetes_api_objects/config_map.rs
- src/kubernetes_api_objects/dynamic.rs
- src/kubernetes_api_objects/error.rs
- src/kubernetes_api_objects/label_selector.rs
- src/kubernetes_api_objects/object_meta.rs
- src/kubernetes_api_objects/persistent_volume_claim.rs
- src/kubernetes_api_objects/pod.rs
- src/kubernetes_api_objects/pod_template_spec.rs
- src/kubernetes_api_objects/resource.rs
- src/kubernetes_api_objects/resource_requirements.rs
- src/kubernetes_api_objects/service.rs
- src/kubernetes_api_objects/stateful_set.rs
- src/shim_layer/mod.rs
- src/simple_controller.rs
- src/zookeeper_controller.rs
this is still due to verus' missing support for cargo, so we resulting need build dependencies separately
this solution is still clearly imperfect, but should be more robust because it does not directly depend on the rlibs deps in cargo's target/deps
> Change the verified crate to only depend on deps-hack, which simplifies the build

- src/controller_examples/simple_controller/exec/reconciler.rs
- src/controller_examples/simple_controller/spec/reconciler.rs
- src/controller_examples/zookeeper_controller/exec/reconciler.rs
- src/controller_examples/zookeeper_controller/spec/reconciler.rs
- src/kubernetes_api_objects/api_method.rs
- src/kubernetes_api_objects/dynamic.rs
- src/kubernetes_api_objects/error.rs
- src/kubernetes_cluster/proof/kubernetes_api_liveness.rs
- src/kubernetes_cluster/spec/client.rs
- src/kubernetes_cluster/spec/kubernetes_api/state_machine.rs
- src/kubernetes_cluster/spec/message.rs
- src/shim_layer/mod.rs
To get closer to how Kubernetes handles creation requests in reality, this PR makes two major changes: (1) the creation request will carry a namespace field, and (2) the k8s API will check whether the namespace of the provided object matches the namespace sent on the creation request; if not, the k8s API will reject the request with the error BadRequest.
Currently the k8s API state machine handles creation requests as follows:
(1) if the namespace set in the provided object does not match the namespace sent on the creation request, then return BadRequest error, else go to (2)
(2) if the object already exists, then return AlreadyExists error, else go to (3)
(3) creates the object
The current specification for how to handle creation requests is still not perfect yet because there are other …
> Revise the k8s API spec to check namespace when creating objects

- src/kubernetes_api_objects/api_method.rs
- src/kubernetes_api_objects/dynamic.rs
- src/kubernetes_api_objects/error.rs
- src/kubernetes_api_objects/object_meta.rs
- src/kubernetes_cluster/spec/client.rs
- src/kubernetes_cluster/spec/kubernetes_api/common.rs
- src/kubernetes_cluster/spec/kubernetes_api/state_machine.rs
- src/kubernetes_cluster/spec/message.rs
Revise the Kubernetes API state machine to support handling update requests.
In short, each update request replaces one existing object stored in etcd. The key of handling update in Kubernetes is to check and update the resource version of each object correctly. The resource version is used for multi-version concurrency control in Kubernetes and etcd. Each object has a resource version number and each update to the object increases the resource version. Only the update request that carries the current resource version of the object can successfully update the object.
This versioning mechanism is very important to prove the object created/updated by the controller remains unchanged: suppose the controller always gets the object and then updates the object with the resource version from the …
> Specify Kubernetes API's update operations

- .gitignore
- src/controller_examples/simple_controller/spec/custom_resource.rs
- src/controller_examples/zookeeper_controller/exec/reconciler.rs
- src/controller_examples/zookeeper_controller/spec/zookeepercluster.rs
- src/kubernetes_api_objects/config_map.rs
- src/kubernetes_api_objects/error.rs
- src/kubernetes_api_objects/label_selector.rs
- src/kubernetes_api_objects/marshal.rs
- src/kubernetes_api_objects/object_meta.rs
- src/kubernetes_api_objects/persistent_volume_claim.rs
- src/kubernetes_api_objects/pod.rs
- src/kubernetes_api_objects/pod_template_spec.rs
- src/kubernetes_api_objects/resource.rs
- src/kubernetes_api_objects/resource_requirements.rs
- src/kubernetes_api_objects/service.rs
- src/kubernetes_api_objects/stateful_set.rs
- src/kubernetes_cluster/spec/distributed_system.rs
In case that they may receive an object or a value that is an unexpected type or misses certain fields or has fields with unexpected types, we make the two methods `from_dynamic_object()` and `marshal()` return `Result<Self, Error>`.
In exec code, just check whether the `try_parse` succeed. In spec code, we have to reason about different cases. Because I divide the error into two types, in addition to the way of converting k8s objects to dynamic objects, the `Error` returned in all the `else` branches (in the spec code `from_dynamic_object()`) present an alternative sequence of the two types of errors, which is rather tedious.
> Make from_dynamic_object and unmarshal return Result

- reference-controllers/zookeeper-controller/src/main.rs
- reference-controllers/zookeeper-controller/src/resources.rs
The key is to set the `StatefulSetPersistentVolumeClaimRetentionPolicy` field to allow the statefulSet controller to clean up the unused pvc during deletion and downscaling.
There are two fields in `StatefulSetPersistentVolumeClaimRetentionPolicy`: `when_deleted` controls whether to delete the pvcs if the statefulset is deleted, and `when_scaled` controls whether to delete the pvcs which is not used by any pod (the pod that previously used the pvc has been deleted). Note that `when_scaled` will also block upscaling until the pvc gets delete to prevent the pod from using stale pvc. More information can be found here: https://kubernetes.io/blog/2021/12/16/kubernetes-1-23-statefulset-pvc-auto-deletion/
`StatefulSetPersistentVolumeClaimRetentionPolicy` is still in alpha stage for Kubernetes …
> Add downscaling support to the reference Zookeeper controller

- src/controller_examples/simple_controller/spec/custom_resource.rs
- src/controller_examples/zookeeper_controller/spec/zookeepercluster.rs
- src/kubernetes_api_objects/config_map.rs
- src/kubernetes_api_objects/persistent_volume_claim.rs
- src/kubernetes_api_objects/pod.rs
- src/kubernetes_api_objects/resource.rs
- src/kubernetes_api_objects/service.rs
- src/kubernetes_api_objects/stateful_set.rs
This PR adds a trusted lemma `spec_integrity_is_preserved_by_marshal` to each Kubernetes object, which says that the spec field of each object, after marshal and unmarshal, remains unchanged.
The main purpose is to help simplify reasoning about any execution where the controller creates an object and later gets the object and makes decisions based on the object's spec field. This lemma can help prove that the object's spec remains the same as when the controller creates the object if no updates happen to the object.
The existing lemma `to_dynamic_preserves_integrity` seems can do the same job but actually not: every time when creating or updating the object, the k8s API state machine will set certain fields in metadata such as resource_version, so the DynamicObject stored in etcd is not …
> Add trusted lemma `spec_integrity_is_preserved_by_marshal` to each Kubernetes object

- src/controller_examples/zookeeper_controller/common/mod.rs
- src/controller_examples/zookeeper_controller/exec/reconciler.rs
- src/controller_examples/zookeeper_controller/spec/reconciler.rs
- src/kubernetes_api_objects/config_map.rs
- src/kubernetes_api_objects/dynamic.rs
- src/kubernetes_api_objects/error.rs
- src/kubernetes_api_objects/persistent_volume_claim.rs
- src/kubernetes_api_objects/pod.rs
- src/kubernetes_api_objects/service.rs
- src/kubernetes_api_objects/stateful_set.rs
- src/shim_layer/mod.rs
In `reconcile_core` of the zookeeper controller, after creating config map, first send a get request to check whether the statefulset already exists in etcd.
> Update statefulset for zookeeper controller

- src/controller_examples/rabbitmq_controller/spec/rabbitmqcluster.rs
- src/controller_examples/simple_controller/spec/custom_resource.rs
- src/controller_examples/zookeeper_controller/spec/reconciler.rs
- src/controller_examples/zookeeper_controller/spec/zookeepercluster.rs
- src/kubernetes_api_objects/config_map.rs
- src/kubernetes_api_objects/persistent_volume_claim.rs
- src/kubernetes_api_objects/pod.rs
- src/kubernetes_api_objects/resource.rs
- src/kubernetes_api_objects/role.rs
- src/kubernetes_api_objects/role_binding.rs
- src/kubernetes_api_objects/secret.rs
- src/kubernetes_api_objects/service.rs
- src/kubernetes_api_objects/service_account.rs
- src/kubernetes_api_objects/stateful_set.rs
Previously kind() was implemented as a method, which is unnecessary because it does not need any object information. This PR changes it to an associated function of the ResourceView trait.
> Make kind() an associated function, instead of a method

- src/kubernetes_cluster/proof/kubernetes_api_liveness.rs
- src/kubernetes_cluster/spec/distributed_system.rs
- src/pervasive_ext/mod.rs
- src/pervasive_ext/multiset_lemmas.rs
- src/temporal_logic/rules.rs
This PR proves that from any arbitrary state (`true_pred()`), all the APIRequest messages sent to the Kubernetes API with a chan_id smaller than a specific nat will eventually leave the network.
This lemma is particularly important when proving the object remains in a particular state stably given that update operations are supported in the Kubernetes API state machine. Although it is obvious that the controller always tries to maintain the object in a stable state (by updating the object with the same spec, assuming the CR remains unchanged),
we also need to somehow show that there are no other update requests in the network that can drive the object to a different state -- such requests might come from the previously crashed controller (they crash right after sending out an update …
> Prove pending requests with old chan_id eventually are all gone

- src/kubernetes_cluster/spec/kubernetes_api/state_machine.rs
This is to reflect Kubernetes' update behavior that if there is no change to the object, the resource version won't increase.
> Revise update handling spec to support noop

- src/kubernetes_api_objects/mod.rs
- src/kubernetes_api_objects/object_meta.rs
- src/kubernetes_api_objects/owner_reference.rs
owner reference type is ready to be used.
Another PR will attach owner reference to rabbitmq and zookeeper controllers.
> Add wrapper and spec for Kubernetes owner reference

- src/controller_examples/rabbitmq_controller/common/mod.rs
- src/controller_examples/rabbitmq_controller/exec/reconciler.rs
- src/controller_examples/rabbitmq_controller/spec/reconciler.rs
- src/kubernetes_api_objects/stateful_set.rs
- In the official rabbitmq controller, only scale-up is supported. When user wants to scale down, rabbitmq controller will reject the request and return `nil` in reconciliation loop. Currently, in our controller, an error will be returned.
- For scale up, the official rabbitmq controller will execute a command `rabbitmq-queues rebalance all`. This command is trying to split different queues' leader to different nodes, which will utilize resources more efficiently. However, this is not necessary if we only want the cluster to perform right functionality.
> Support update operations for rabbitmq controller

- deploy/zookeeper/crd.yaml
- reference-controllers/zookeeper-controller/src/main.rs
- reference-controllers/zookeeper-controller/src/resources.rs
- reference-controllers/zookeeper-controller/src/zookeepercluster_types.rs
- src/controller_examples/zookeeper_controller/exec/mod.rs
- src/controller_examples/zookeeper_controller/exec/reconciler.rs
- src/controller_examples/zookeeper_controller/exec/zookeepercluster.rs
- src/controller_examples/zookeeper_controller/spec/reconciler.rs
- src/controller_examples/zookeeper_controller/spec/zookeepercluster.rs
- src/deps_hack/src/lib.rs
- src/zookeeper_controller.rs
Split the ZookeeperCluster and its ghost version into different folders and rename `replica` to `replicas`.
> Cosmetic changes in ZookeeperCluster

- src/controller_examples/rabbitmq_controller/spec/rabbitmqcluster.rs
- src/controller_examples/simple_controller/spec/custom_resource.rs
- src/controller_examples/zookeeper_controller/spec/zookeepercluster.rs
- src/kubernetes_api_objects/config_map.rs
- src/kubernetes_api_objects/persistent_volume_claim.rs
- src/kubernetes_api_objects/pod.rs
- src/kubernetes_api_objects/resource.rs
- src/kubernetes_api_objects/role.rs
- src/kubernetes_api_objects/role_binding.rs
- src/kubernetes_api_objects/secret.rs
- src/kubernetes_api_objects/service.rs
- src/kubernetes_api_objects/service_account.rs
- src/kubernetes_api_objects/stateful_set.rs
The `spec()` is a trait method of ResourceView trait. This is mainly used to expose the spec content of a K8s object in the Anvil built in lemmas where we don't know the concrete type of a ResourceView object.
> Implement spec() for K8s object types

- src/controller_examples/zookeeper_controller/proof/liveness.rs
- src/controller_examples/zookeeper_controller/proof/safety.rs
- src/kubernetes_cluster/proof/cluster.rs
- src/kubernetes_cluster/proof/controller_runtime_eventual_safety.rs
- src/kubernetes_cluster/proof/mod.rs
Generalize the two lemmas lemma_true_leads_to_always_the_object_in_schedule_has_spec_as and lemma_true_leads_to_always_the_object_in_reconcile_has_spec_as and move them to controller_runtime_eventual_safety.rs.
> Generalize lemmas on reconciled/scheduled cr objects

- src/controller_examples/zookeeper_controller/proof/liveness.rs
- src/kubernetes_cluster/proof/cluster.rs
- src/kubernetes_cluster/proof/controller_runtime_eventual_safety.rs
- src/kubernetes_cluster/proof/controller_runtime_liveness.rs
- src/state_machine/action.rs
- src/temporal_logic/rules.rs
Previously, proving wf1 for schedule_controller_reconcile is cumbersome because we need `desired_state_is` (or `desired_state_exists`) to satisfy this action's precondition, but `desired_state_is` is in the spec and cannot be directly used to satisfy the precondition when applying wf1.
This PR introduces a new lemma to "borrow" the conditions from the spec to apply wf1, which makes it simpler to reason about schedule_controller_reconcile.
> Simplify reasoning about schedule_controller_reconcile

- src/controller_examples/simple_controller/proof/liveness.rs
- src/controller_examples/zookeeper_controller/proof/liveness.rs
- src/kubernetes_cluster/proof/cluster.rs
- src/kubernetes_cluster/proof/controller_runtime_eventual_safety.rs
- src/temporal_logic/rules.rs
Finish the stable proofs (which were left as assumed in the liveness proof). Also rename related lemmas to the form of `x_is_stable`.
In future work, some lemmas/predicates can be made more generic to avoid redundancy.
> Prove specs are stable as part of liveness proof

- src/controller_examples/zookeeper_controller/proof/common.rs
- src/controller_examples/zookeeper_controller/proof/liveness.rs
- src/controller_examples/zookeeper_controller/proof/safety.rs
- src/controller_examples/zookeeper_controller/proof/terminate.rs
The general idea to simplify the proof is to find common patterns of what happens in `reconcile_core`.
The current `reconcile_core` of zookeeper controller is simple, so that I can come up with a single pattern that the controller starts from a state, reads the response, then generates a request and enters the next state.
> Simplify the termination and safety proof of zookeeper

- src/shim_layer/mod.rs
Previously we translate the kube error types to APIError (an enum that represents different kinds of errors k8s might return) by checking its `code`. This PR changes it by checking `reason`, which is more straightforward and robust.
> Translate kube error to Verus-friendly type by `reason`, instead of `code`

- src/controller_examples/zookeeper_controller/proof/liveness.rs
- src/controller_examples/zookeeper_controller/proof/safety.rs
- src/controller_examples/zookeeper_controller/proof/terminate.rs
- src/kubernetes_api_objects/error.rs
- src/kubernetes_cluster/proof/cluster.rs
- src/kubernetes_cluster/proof/controller_runtime_safety.rs
- src/kubernetes_cluster/proof/kubernetes_api_liveness.rs
- src/kubernetes_cluster/spec/cluster.rs
- src/kubernetes_cluster/spec/message.rs
In this PR, we add a new action to the state machine that supports kubernetes to stay busy and reject the received request (send an error response).
> Support k8s busy action and fix the liveness proof after that

- src/controller_examples/zookeeper_controller/proof/common.rs
- src/controller_examples/zookeeper_controller/proof/liveness.rs
- src/controller_examples/zookeeper_controller/proof/safety.rs
- src/controller_examples/zookeeper_controller/proof/terminate.rs
- src/kubernetes_cluster/proof/controller_runtime.rs
- src/kubernetes_cluster/proof/controller_runtime_liveness.rs
- src/kubernetes_cluster/proof/controller_runtime_safety.rs
- src/temporal_logic/rules.rs
In this PR, I mainly do two things:
1. Some straightforward simplifications for liveness proof of zookeeper controller.
2. Apply some lemmas (properties) of zookeeper controller to all controllers.
> Simplify liveness proof of zookeeper controller

- src/controller_examples/zookeeper_controller/proof/liveness.rs
- src/kubernetes_cluster/proof/controller_runtime_liveness.rs
Previously, I add `next_state != init` to the preconditions of some lemmas for disabling the `run_scheduled_reconcile` action. Now I find this is really not needed because the state before `~>` requires that the reconcile already starts.
> Remove the next_state != init preconditions for some lemmas

- reference-controllers/rabbitmq-controller/src/main.rs
- reference-controllers/rabbitmq-controller/src/server_configmap.rs
- reference-controllers/rabbitmq-controller/src/statefulset.rs
Support upgrade for unverified rabbitmq controller. Details are shown in #175 .
Add code to update StatefulSet.spec.replicas and StatefulSet.spec.image.
The replicas field is based on rabbitmq.spec.replicas and the image field is based on rabbitmq.spec.image.
> Support upgrade for unverified rabbitmq controller

- .github/workflows/regression-testing.yml
- src/controller_examples/rabbitmq_controller/mod.rs
- src/controller_examples/rabbitmq_controller/proof/common.rs
- src/controller_examples/rabbitmq_controller/proof/liveness.rs
- src/controller_examples/rabbitmq_controller/proof/safety.rs
- src/controller_examples/rabbitmq_controller/proof/terminate.rs
- src/controller_examples/rabbitmq_controller/spec/reconciler.rs
- src/controller_examples/simple_controller/proof/liveness.rs
- src/controller_examples/simple_controller/proof/safety.rs
- src/controller_examples/simple_controller/proof/shared.rs
- src/controller_examples/simple_controller/spec/reconciler.rs
- src/controller_examples/zookeeper_controller/mod.rs
- src/controller_examples/zookeeper_controller/proof/common.rs
- src/controller_examples/zookeeper_controller/proof/liveness/helper_invariants.rs
- src/controller_examples/zookeeper_controller/proof/liveness/liveness_property.rs
- src/controller_examples/zookeeper_controller/proof/liveness/terminate.rs
- src/controller_examples/zookeeper_controller/proof/safety/deletion_safety.rs
- src/controller_examples/zookeeper_controller/spec/reconciler.rs
- src/kubernetes_cluster/proof/controller_runtime.rs
- src/kubernetes_cluster/proof/controller_runtime_liveness.rs
- src/kubernetes_cluster/proof/controller_runtime_safety.rs
- src/kubernetes_cluster/spec/controller/common.rs
- src/kubernetes_cluster/spec/controller/controller_runtime.rs
- src/reconciler/spec/reconciler.rs
The core idea is that we add execution of external functions to the `continue_reconcile` action. 
To support this, we add `lib_response` to the controller state struct. Then there are three types of actions in `continue_reconcile` which are categorized based on the return request of `reconcile_core`:
1. If the `reconcile_core` returns a k8s api request, then we set the `pending_req_msg` field as before;
2. If the `reconcile_core` returns a external request, then we directly call the external library to process the request, which means we make the two steps done in one action. Then we set the `lib_response` field to the returned response.
3. If the `reconcile_core` returns no request, just leave both of the fields `Option::None`.
We should be careful about the preconditions of …
> Support external APIs in the state machine

- src/controller_examples/rabbitmq_controller/proof/common.rs
- src/controller_examples/rabbitmq_controller/proof/liveness.rs
- src/controller_examples/rabbitmq_controller/proof/terminate.rs
- src/controller_examples/zookeeper_controller/mod.rs
- src/controller_examples/zookeeper_controller/proof/common.rs
- src/controller_examples/zookeeper_controller/proof/liveness/liveness_property.rs
- src/controller_examples/zookeeper_controller/proof/liveness/mod.rs
- src/controller_examples/zookeeper_controller/proof/liveness/terminate.rs
- src/controller_examples/zookeeper_controller/proof/mod.rs
- src/kubernetes_cluster/proof/controller_runtime.rs
- src/kubernetes_cluster/proof/controller_runtime_liveness.rs
- src/kubernetes_cluster/proof/controller_runtime_safety.rs
After adding a new field to `ZookeeperReconcileState`, describing a specific reconcile state becomes more troublesome. However, sometimes we only care about part of the reconcile state, and that is enough for proving certain properties. Thus, we introduce closure to replace a concrete reconcile state in those controller runtime lemmas.
> Use closure to describe reconcile states in controller runtime proof

- src/controller_examples/rabbitmq_controller/proof/safety.rs
- src/controller_examples/rabbitmq_controller/spec/reconciler.rs
- src/controller_examples/simple_controller/spec/reconciler.rs
- src/controller_examples/zookeeper_controller/exec/reconciler.rs
- src/controller_examples/zookeeper_controller/exec/zookeeper_lib/lib.rs
- src/controller_examples/zookeeper_controller/spec/reconciler.rs
- src/controller_examples/zookeeper_controller/spec/zookeeper_lib.rs
- src/kubernetes_cluster/proof/controller_runtime.rs
- src/kubernetes_cluster/proof/controller_runtime_safety.rs
- src/kubernetes_cluster/spec/controller/common.rs
- src/kubernetes_cluster/spec/controller/controller_runtime.rs
- src/reconciler/exec/external.rs
- src/reconciler/exec/io.rs
- src/reconciler/exec/reconciler.rs
- src/reconciler/spec/reconciler.rs
- src/shim_layer/mod.rs
- src/zookeeper_controller.rs
The spec models the data stored in zookeeper as a map whose key is the zk node path. Calling the zk API to write to the zk node will insert the key-value pair into the map. The spec is highly simplified compared to the real zookeeper and is tailored for the use of the zookeeper controller.
There are still many important problems left for future PRs to deal with, such as: (1) what is our assumption on the external APIs? Do we assume they always return the result successfully, or they might return some transient error (and eventually get back to normal)? Or some other assumptions? (2) The external API's state and result might depend on the state of the k8s objects. Like, if the zk pods are not ready then the zk API won't work. Should we try to specify such dependencies?
> Add simplified specs to the zookeeper external library

- deploy/fluent/crd.yaml
- deploy/fluent/fluentbit.yaml
- src/controller_examples/fluent_controller/common/mod.rs
- src/controller_examples/fluent_controller/exec/fluentbit.rs
- src/controller_examples/fluent_controller/exec/mod.rs
- src/controller_examples/fluent_controller/exec/reconciler.rs
- src/controller_examples/fluent_controller/mod.rs
- src/controller_examples/fluent_controller/spec/fluentbit.rs
- src/controller_examples/fluent_controller/spec/mod.rs
- src/controller_examples/fluent_controller/spec/reconciler.rs
- src/deps_hack/src/lib.rs
- src/fluent_controller.rs
- src/kubernetes_api_objects/pod.rs
The fluent controller, built on top of Anvil, behaves almost the same as the reference unverified fluent controller, except that: (1) The FluentBit configuration is passed to the controller through the CR's fields, and (2) The ported controller uses Role and RoleBinding, instead of Cluster and ClusterRoleBinding, because Anvil doesn't support cluster-scoped resources for now.
> Port the fluent controller

- deploy/fluent/crd.yaml
- src/controller_examples/fluent_controller/exec/fluentbit.rs
- src/controller_examples/fluent_controller/exec/reconciler.rs
- src/controller_examples/fluent_controller/spec/fluentbit.rs
- src/controller_examples/fluent_controller/spec/reconciler.rs
- src/deps_hack/Cargo.lock
- src/deps_hack/Cargo.toml
- src/deps_hack/src/lib.rs
- src/kubernetes_api_objects/pod.rs
- src/kubernetes_api_objects/resource_requirements.rs
The new field `resources` allows the user to specify CPU/memory allocation to the running fluent bit process. Adding the new field doesn't affect the control flow and only requires small changes to the code base, mainly for defining new wrapper and ghost types.
> Add `resources` to FluentBit

- src/kubernetes_api_objects/dynamic.rs
- src/kubernetes_api_objects/object_meta.rs
- src/kubernetes_api_objects/owner_reference.rs
- src/kubernetes_cluster/spec/kubernetes_api/common.rs
- src/kubernetes_cluster/spec/kubernetes_api/state_machine.rs
In Kubernetes, each object has an uid (unique id) which is used to differentiate it from any object that shares the same name and was previously deleted. For ease of specification and proof, we use nat, instead of a string (used in real implementation), to represent uid for each object.
Besides, we also simplify the state machine to make it easier to extend it with built-in controllers. The transition_by_etcd function now returns the new k8s api state and the output message. Built-in controllers later will be specified as other actions of the k8s api state machine (just like handle_request).
> Allocate uid to each created object in k8s API state machine

- doc/finalizers.md
This will be used as a reference for us to complete the specification of how the API server handles deletion in Kubernetes.
> Document how finalizers affect deletion in Kubernetes

- src/controller_examples/fluent_controller/exec/fluentbit.rs
- src/controller_examples/fluent_controller/exec/reconciler.rs
- src/controller_examples/fluent_controller/spec/fluentbit.rs
- src/controller_examples/fluent_controller/spec/reconciler.rs
With the owner reference that points to the FluentBit object, if the FluentBit is deleted, all the owned objects (role, service account, role binding, secret, and daemon set) will be automatically deleted by the garbage collector as well.
> Set owner reference for the FluentBit controller

- src/controller_examples/rabbitmq_controller/proof/liveness.rs
- src/kubernetes_api_objects/dynamic.rs
- src/kubernetes_cluster/spec/kubernetes_api/state_machine.rs
The API server will delete the object when handling an update request if this update removes all the finalizers from the object and the object has a deletion timestamp.
We also mark some lemmas as external_body and leave them for future work.
> Specify delete-during-update

- src/controller_examples/rabbitmq_controller/proof/liveness/helper_invariants/owner_ref.rs
- src/kubernetes_cluster/spec/kubernetes_api/state_machine.rs
This PR makes some small changes to further complete the API server specification:
- Specify unconditional update which decides whether the object can be updated without providing a resource version.
- Revise the conditions on checking whether an update is a noop-update (which does not change the resource version).
There could be more changes to the API server specifications later when we support more fields.
> Cosmetic changes in API server spec

- src/controller_examples/rabbitmq_controller/proof/common.rs
- src/controller_examples/rabbitmq_controller/proof/liveness/helper_invariants/invariants.rs
- src/controller_examples/rabbitmq_controller/proof/liveness/helper_invariants/owner_ref.rs
- src/controller_examples/rabbitmq_controller/proof/liveness/liveness.rs
- src/controller_examples/rabbitmq_controller/proof/liveness/terminate.rs
- src/controller_examples/simple_controller/proof/liveness.rs
- src/controller_examples/zookeeper_controller/proof/liveness/helper_invariants.rs
- src/controller_examples/zookeeper_controller/proof/liveness/liveness_property.rs
- src/controller_examples/zookeeper_controller/proof/liveness/terminate.rs
- src/kubernetes_api_objects/object_meta.rs
- src/kubernetes_cluster/proof/builtin_controllers.rs
- src/kubernetes_cluster/proof/cluster_safety.rs
- src/kubernetes_cluster/proof/controller_runtime_eventual_safety.rs
- src/kubernetes_cluster/proof/controller_runtime_liveness.rs
- src/kubernetes_cluster/proof/controller_runtime_safety.rs
- src/kubernetes_cluster/proof/kubernetes_api_liveness.rs
- src/kubernetes_cluster/proof/message.rs
- src/kubernetes_cluster/proof/mod.rs
- src/kubernetes_cluster/spec/builtin_controllers/garbage_collector.rs
- src/temporal_logic/rules.rs
This PR first finishes the proof of all invariants used in the liveness proof of rabbitmq controller. Besides that, I also simplify the proof by removing some obviously redundant code and writing some common functions for different objects.
Also, I move the reasoning of gc action to the cluster module, so that all the controllers can use the lemma to prove that eventually only object with valid owner reference will exists.
> Prove all the invariants used for Rabbitmq controller liveness

- src/kubernetes_api_objects/owner_reference.rs
- src/kubernetes_cluster/proof/kubernetes_api_liveness.rs
- src/kubernetes_cluster/spec/kubernetes_api/state_machine.rs
Add the specification for checking whether the controller has multiple controller owner references, and if so, reject the creation/update requests. The corresponding validation implementation in Kubernetes can be found at https://github.com/kubernetes/kubernetes/blob/v1.26.3/staging/src/k8s.io/apimachinery/pkg/api/validation/objectmeta.go#L92-L108.
> Validate that there is only one controller owner reference

- src/controller_examples/rabbitmq_controller/proof/safety/safety.rs
- src/kubernetes_api_objects/error.rs
- src/kubernetes_api_objects/object_meta.rs
- src/kubernetes_cluster/spec/kubernetes_api/state_machine.rs
The new validation rule states that if the object is marked to be deleted (`.metadata.deletion_timestamp.is_Some()`), then one cannot update the object by adding more finalizers to it.
> Add validation for finalizers

- src/controller_examples/rabbitmq_controller/proof/helper_invariants/invariants.rs
- src/controller_examples/rabbitmq_controller/proof/safety/safety.rs
- src/kubernetes_api_objects/common.rs
- src/kubernetes_api_objects/dynamic.rs
- src/kubernetes_api_objects/object_meta.rs
- src/kubernetes_api_objects/owner_reference.rs
- src/kubernetes_cluster/proof/kubernetes_api_safety.rs
This change will be useful later if the controller needs to get the resource version from some object and use it (as a label or annotation). To use `int_to_string_view()` in the postcondition of `resource_version()`, we also change the Uid/ResourceVersion type to int, instead of nat, which causes no difference to the proof.
> Make `resource_version()` return string, instead of integer

- src/external_api/spec.rs
- src/kubernetes_api_objects/resource.rs
- src/pervasive_ext/to_view.rs
- src/reconciler/spec/reconciler.rs
This is to avoid errors reported by Verus checks which are newly introduced by https://github.com/verus-lang/verus/commit/77636b62408121fddba36fb952c9987b4f9138f5.
> Remove open/closed from empty spec functions

- e2e/src/common.rs
- e2e/src/rabbitmq_e2e.rs
- e2e/src/zookeeper_e2e.rs
- src/controller_examples/zookeeper_controller/exec/reconciler.rs
- src/controller_examples/zookeeper_controller/spec/reconciler.rs
Add scaling tests for both zookeeper and rabbitmq, and add perf test for rabbitmq. Also fix a liveness bug in the zookeeper controller implementation, and remove unused entry `CLUSTER_SIZE` from the env.sh in the config map object.
> Add scaling tests and perf tests for zookeeper and rabbitmq controllers

- deploy/zookeeper/crd.yaml
- src/controller_examples/zookeeper_controller/spec/types.rs
This fixes the bug that the controller fails to scale up the zookeeper cluster from 0 replicas. More details can be found in #269 .
> Disallow downscale to 0 for zookeeper

- src/controller_examples/rabbitmq_controller/exec/reconciler.rs
- src/controller_examples/rabbitmq_controller/exec/resource/common.rs
- src/controller_examples/rabbitmq_controller/exec/resource/config_map.rs
- src/controller_examples/rabbitmq_controller/exec/resource/default_user_secret.rs
- src/controller_examples/rabbitmq_controller/exec/resource/erlang_cookie.rs
- src/controller_examples/rabbitmq_controller/exec/resource/headless_service.rs
- src/controller_examples/rabbitmq_controller/exec/resource/rabbitmq_plugins.rs
- src/controller_examples/rabbitmq_controller/exec/resource/role.rs
- src/controller_examples/rabbitmq_controller/exec/resource/role_binding.rs
- src/controller_examples/rabbitmq_controller/exec/resource/service.rs
- src/controller_examples/rabbitmq_controller/exec/resource/service_account.rs
- src/controller_examples/rabbitmq_controller/exec/resource/stateful_set.rs
- src/controller_examples/rabbitmq_controller/proof/common.rs
- src/controller_examples/rabbitmq_controller/proof/liveness/mod.rs
- src/controller_examples/rabbitmq_controller/proof/liveness/property.rs
- src/controller_examples/rabbitmq_controller/proof/liveness/terminate.rs
- src/controller_examples/rabbitmq_controller/proof/mod.rs
- src/controller_examples/rabbitmq_controller/proof/predicate.rs
- src/controller_examples/rabbitmq_controller/spec/reconciler.rs
- src/controller_examples/rabbitmq_controller/spec/resource/config_map.rs
- src/controller_examples/rabbitmq_controller/spec/resource/default_user_secret.rs
- src/controller_examples/rabbitmq_controller/spec/resource/erlang_cookie.rs
- src/controller_examples/rabbitmq_controller/spec/resource/headless_service.rs
- src/controller_examples/rabbitmq_controller/spec/resource/rabbitmq_plugins.rs
- src/controller_examples/rabbitmq_controller/spec/resource/role.rs
- src/controller_examples/rabbitmq_controller/spec/resource/role_binding.rs
- src/controller_examples/rabbitmq_controller/spec/resource/service.rs
- src/controller_examples/rabbitmq_controller/spec/resource/service_account.rs
- src/controller_examples/rabbitmq_controller/spec/resource/stateful_set.rs
This PR proves the termination of rabbitmq controller. To facilitate this, one notable change is that I move the reconcile step change from method `state_after_create_or_update` to the reconciler.
> Prove termination for rabbitmq controller

- src/kubernetes_api_objects/error.rs
- src/kubernetes_cluster/proof/cluster.rs
- src/kubernetes_cluster/proof/controller_runtime_safety.rs
- src/kubernetes_cluster/proof/kubernetes_api_liveness.rs
- src/kubernetes_cluster/proof/message.rs
- src/kubernetes_cluster/spec/cluster.rs
- src/kubernetes_cluster/spec/cluster_state_machine.rs
- src/shim_layer/controller_runtime.rs
This PR considers resource version conflicts as a type of transient error and assumes that such conflicts eventually stop hindering our custom controller's progress.
Controllers run concurrently and share state. For example, one controller updates `o.spec` while the other one updates `o.status`. Without locking, conflicts could happen when two controllers are trying to update the same object "at the same time" -- if both of them try to update the same version, only one will succeed which increments the version number, so the other one will fail because its version number no longer matches.
It is tedious and takes tremendous effort to specify all kinds of conflicts between our custom controller and built-in controllers. Instead, we treat such conflicts as a transient error that eventually …
> Treat resource version conflict as a transient error

- src/controller_examples/fluent_controller/fluentbit/exec/reconciler.rs
- src/controller_examples/fluent_controller/fluentbit/spec/reconciler.rs
- src/controller_examples/fluent_controller/fluentbit_config/common/mod.rs
- src/controller_examples/fluent_controller/fluentbit_config/exec/reconciler.rs
- src/controller_examples/fluent_controller/fluentbit_config/spec/reconciler.rs
- src/controller_examples/zookeeper_controller/exec/reconciler.rs
It includes (1) overwriting finalizers and owner references when updating the fluent bit/fluent big config subresources, and (2) supporting update operations for the fluent bit config reconciler.
> Cosmetic changes to fluent controller

- .gitignore
- e2e/src/rabbitmq_e2e.rs
- src/controller_examples/rabbitmq_controller/exec/resource/service.rs
- src/controller_examples/rabbitmq_controller/spec/resource/service.rs
This is to avoid a naming conflict bug when there are multiple rabbitmq cluster (cr) instances. Suppose one instance is called `foo` and the other is called `foo-nodes`. Before this change, the headless service of the first cr will be called `foo-nodes` and the client service of the second cr will be called `foo-nodes` as well. Thus, the reconciler instances for the two crs will start to compete on the `foo-nodes` service, causing oscillation problems and liveness violations.
This renaming fixes the problem. From now on, for every rabbitmq cluster instance, its headless and client services will never collide with the services of other rabbitmq cluster instances.
> Fix oscillation problem by renaming the client service of rabbitmq

- deploy/rabbitmq/crd.yaml
- src/controller_examples/rabbitmq_controller/exec/resource/headless_service.rs
- src/controller_examples/rabbitmq_controller/exec/resource/role_binding.rs
- src/controller_examples/rabbitmq_controller/exec/resource/service.rs
- src/controller_examples/rabbitmq_controller/exec/resource/stateful_set.rs
- src/controller_examples/rabbitmq_controller/exec/types.rs
- src/controller_examples/rabbitmq_controller/proof/helper_invariants/proof.rs
- src/controller_examples/rabbitmq_controller/spec/resource/headless_service.rs
- src/controller_examples/rabbitmq_controller/spec/resource/role_binding.rs
- src/controller_examples/rabbitmq_controller/spec/resource/service.rs
- src/controller_examples/rabbitmq_controller/spec/resource/stateful_set.rs
- src/controller_examples/rabbitmq_controller/spec/types.rs
- src/deps_hack/src/lib.rs
- src/kubernetes_api_objects/persistent_volume_claim.rs
- src/kubernetes_api_objects/service.rs
This PR makes the following changes:
1. Change the update logic for RoleBiding object to avoid updating its role_ref
2. Change the update logic for main and headless service objects to avoid updating its cluster ip
3. Fix the immutability bugs of storage_class_name and pod_management_policy: these two fields should not be nullable since they should be immutable (the immutable validation rules don't work well for nullable fields)
> Cosmetic changes to rabbitmq controller

- .gitignore
- src/controller_examples/rabbitmq_controller/proof/helper_invariants/owner_ref.rs
- src/controller_examples/rabbitmq_controller/proof/helper_invariants/predicate.rs
- src/controller_examples/rabbitmq_controller/proof/helper_invariants/proof.rs
- src/controller_examples/rabbitmq_controller/proof/helper_invariants/unchangeable.rs
- src/controller_examples/rabbitmq_controller/proof/helper_invariants/validation.rs
- src/controller_examples/rabbitmq_controller/proof/safety/safety.rs
- src/kubernetes_cluster/proof/message.rs
This PR tries to accelerate some time-consuming lemmas in the proof of rabbitmq controller. The approaches and observations are as follows:
- Break down the proof into multiple methods. Suppose we have a `lemma_a` which runs for $n$ seconds. We can move part of it into a new lemma `lemma_b` and call `lemma_b` inside `lemma_a`. Then `lemma_a` and `lemma_b` run for $n'$ and $m$ seconds separately. The interesting thing is that usually $n'+m < n$.
- Make the lemma simpler. We tend to carry multiple things using one lemma (one spec in most cases) if they can be easily proved together. However, sometimes this makes things worse. We can first prove the part that is independent of the rest and get a simpler lemma first. [This lemma](https://github.com/vmware-research/verifiable-controllers/blob/8 …
> Accelerate some lemmas in rabbitmq proof

- deploy/zookeeper/crd.yaml
- Adding validation rule for the ZooKeeper configuration `syncLimit` to be greater or equal to 1. 
- Adding validation rule for the ZooKeeper configuration `minSessionTimeout` to be less or equal to `maxSessionTimeout`.
These two validation rules prevents ZooKeeper misconfigurations and fix the liveness bug.
> Add validations for ZooKeeper configuration parameters

- src/controller_examples/fluent_controller/fluentbit_config/proof/liveness/resource_match.rs
- src/controller_examples/rabbitmq_controller/proof/helper_invariants/proof.rs
- src/kubernetes_api_objects/exec/container.rs
- src/kubernetes_api_objects/exec/pod.rs
- src/kubernetes_api_objects/spec/container.rs
- src/kubernetes_api_objects/spec/pod.rs
Add `security_context` and `args` to `Container`.
Add `image_pull_secrets` to `PodSpec`.
> Add fields to k8s api objects

- reproduce-verification-result.sh
- tools/count-anvil-loc.py
- tools/count-loc.py
- tools/gen-t1-loc.py
- tools/gen-t1-t2-lines.py
- tools/gen-t1-t2-time.py
- tools/gen-t1-time.py
The newly added script `reproduce-verification-result.sh` will verify the Anvil framework and the three controllers, generate the code size and time to verify as tables, and output the verification result (0 errors expected).
> Add the script for reproducing verification results

- .github/workflows/ci.yml
- deploy/v_replica_set/crd.yaml
- src/controller_examples/v_replica_set_controller/exec/mod.rs
- src/controller_examples/v_replica_set_controller/exec/reconciler.rs
- src/controller_examples/v_replica_set_controller/mod.rs
- src/controller_examples/v_replica_set_controller/trusted/exec_types.rs
- src/controller_examples/v_replica_set_controller/trusted/mod.rs
- src/controller_examples/v_replica_set_controller/trusted/spec_types.rs
- src/controller_examples/v_replica_set_controller/trusted/step.rs
- src/deps_hack/src/lib.rs
- src/kubernetes_api_objects/exec/api_method.rs
- src/kubernetes_api_objects/exec/label_selector.rs
- src/kubernetes_api_objects/exec/object_meta.rs
- src/kubernetes_api_objects/exec/pod.rs
- src/kubernetes_api_objects/exec/pod_template_spec.rs
- src/kubernetes_api_objects/spec/label_selector.rs
- src/kubernetes_api_objects/spec/object_meta.rs
- src/v_replica_set_controller.rs
- src/vstd_ext/string_map.rs
The prototype replica set controller implements the basic scaling up/down functionality. It lists all the pods in the same namespace, filters out the pods that do not match the replica set object's selector, and them create/delete pods to make sure there are `replicas` number of matched pods.
The replica set controller is not verified yet, and there are still more features to implement, such as claiming orphan pods.
> Add a prototype of verified ReplicaSet controller

- discussion/exec-as-spec/specexec.rs
The code is written by @utaal . The goal is to build a macro that takes the exec controller code and outputs its spec version that can be directly used in the proof, so that we do not have to write the controller model each time.
> Add discussion material on exec-as-spec

- src/controller_examples/v_replica_set_controller/model/mod.rs
- src/controller_examples/v_replica_set_controller/model/reconciler.rs
- src/controller_examples/v_replica_set_controller/trusted/liveness_theorem.rs
- src/controller_examples/v_replica_set_controller/trusted/mod.rs
Here I state a basic liveness theorem, based on Eventually Stable Reconciliation, for ReplicaSets. To check whether the cluster state matches the spec, I gather up all pods that match the label selector `selector` and are owned by the ReplicaSet into a Verus set. I then check whether the cardinality of that set is equal to the `replicas` field.
> Add liveness specification for VReplicaSet controller

- src/controller_examples/v_replica_set_controller/exec/reconciler.rs
- src/controller_examples/v_replica_set_controller/model/reconciler.rs
- Add a model reconciler for the `VReplicaSet` controller, modeled after the executable reconciler.
- Prove the implementation conforms to the model
> Add model reconciler and prove conformance for vrs controller

- src/soundness/compositionality/proof.rs
- src/soundness/compositionality/state_machine.rs
This PR makes two major changes to the abstract state machine used for demonstrating compositional proof:
(1) the abstract state machine is no longer hardcoded to two controllers, but takes a sequence of controllers
(2) the first proof obligation no longer constrains *what the cluster is*. Instead, its precondition constrains *what the cluster does* (the producer runs in the cluster and there is no interference).
> Extend the abstract state machine as an array of controllers

- src/soundness/compositionality/proof.rs
- src/soundness/compositionality/state_machine.rs
This PR introduces symmetric lemmas for the consumer and producers parameterized by `cluster` so the compositional proof is no longer hard coded to any particular cluster. This means that the consumer's correctness spec can now be used by any downstream controller in any cluster where the consumer and producers are running and there is no interference.
The generalization comes with some cost: the top-level theorem `consumer_and_producers_are_correct` now seems a bit more complex with extra preconditions to constrain the behavior of other controllers in the input `cluster`. The last precondition (the super long one) says that other controllers will not interfere with the consumer or producers. To identify the "other controllers," we need to introduce the id of the consumer and producers: …
> Generalize the top-level theorem of the compositional proof for any cluster

- src/soundness/compositionality/proof.rs
- src/soundness/compositionality/state_machine.rs
This PR uses `Map` instead of `Seq` to store the controllers in the cluster. The major benefit is that `Map` makes it much easier to state "controllers other than x, y, and z satisfy properties P" by simply removing the entries of x, y, and z from the map and applying P to the resulting map.
One limitation of using `Map` is that we cannot have multiple instances of the same controllers in the cluster. However, in practice this is not a concern: there is no reason to have two identical controllers running in the cluster. The two will conflict and interfere with each other. The common practice is to have only one active instance (the primary) of each controller running, with multiple threads internally handling different pieces of the cluster state, and some other inactive instances as …
> Simplify compositional theorems by using `Map` to represent controllers

- src/soundness/compositionality/examples.rs
- src/soundness/compositionality/mod.rs
- src/soundness/compositionality/proof.rs
- src/soundness/compositionality/state_machine.rs
This PR generalizes the entire compositional proof for any consumer and producers so that we can apply the same lemma to different combinations of consumer and producers.
> Generalize the compositional proof for any consumer and producers

- src/soundness/compositionality/examples.rs
- src/soundness/compositionality/proof.rs
This PR introduces `ControllerSpecGroup` which includes the controller, its key in the `cluster.controllers` map, its temporal property, and its non-interference invariant. This struct helps to simplify the compositional theorems, as we no longer need to carry the `consumer_id`/`producer_ids` along the way.
> Group the spec functions for each controller

- src/soundness/compositionality/examples.rs
- src/soundness/compositionality/proof.rs
This PR introduces a way for developers to compose controllers incrementally when proving the correctness of a cluster of controllers. By "incrementally", we mean that if we already have a proof `P` for the correctness of a controller `foo` and its producers, we can develop another proof for the correctness of controller `bar` that relies on `foo` and its producers on top of `P` by focusing on reasoning about `bar`.
More concretely, this PR introduces:
- `BaseComposition`: a trait with five proof functions (as trait methods) as the proof obligations to compose a consumer and a sequence of producers.
- `IncrementalComposition`: a trait with three proof functions as the proof obligations to incrementally compose a consumer with a sequence of producers (that have already been proved …
> Compose controllers incrementally

- src/conformance_tests/api_server.rs
- src/controller_examples/fluent_controller/fluentbit/proof/helper_invariants/predicate.rs
- src/controller_examples/fluent_controller/fluentbit/trusted/spec_types.rs
- src/controller_examples/fluent_controller/fluentbit_config/proof/helper_invariants/predicate.rs
- src/controller_examples/fluent_controller/fluentbit_config/trusted/spec_types.rs
- src/controller_examples/rabbitmq_controller/proof/helper_invariants/predicate.rs
- src/controller_examples/rabbitmq_controller/trusted/spec_types.rs
- src/controller_examples/v_replica_set_controller/trusted/spec_types.rs
- src/controller_examples/zookeeper_controller/proof/helper_invariants/predicate.rs
- src/controller_examples/zookeeper_controller/trusted/spec_types.rs
- src/executable_model/api_server.rs
- src/executable_model/common.rs
- src/kubernetes_api_objects/exec/common.rs
- src/kubernetes_api_objects/exec/mod.rs
- src/kubernetes_api_objects/exec/prelude.rs
- src/kubernetes_api_objects/spec/common.rs
- src/kubernetes_api_objects/spec/resource.rs
- src/kubernetes_cluster/proof/controller_runtime_liveness.rs
- src/kubernetes_cluster/proof/validation_rule.rs
- src/kubernetes_cluster/spec/api_server/state_machine.rs
- src/v2/kubernetes_cluster/spec/api_server/state_machine.rs
This PR modifies the `Kind` type to let its `CustomResourceKind` variant carry a `StringView`, which can be used to differentiate between different custom resource types. For example, the ZooKeeper controller's CR type should be `CustomResourceKind("zookeeper"@)` while the RabbitMQ controller's should be `CustomResourceKind("rabbitmq"@)`. This is important for state machine v2 because it will take in multiple controllers and multiple custom resource types and we need to differentiate them during the proof.
> Differentiate between different custom resource types

- src/controller_examples/fluent_controller/fluentbit/exec/resource/daemon_set.rs
- src/controller_examples/fluent_controller/fluentbit/proof/helper_invariants/proof.rs
- src/controller_examples/fluent_controller/fluentbit_config/proof/helper_invariants/proof.rs
- src/controller_examples/rabbitmq_controller/proof/helper_invariants/proof.rs
- src/controller_examples/zookeeper_controller/proof/helper_invariants/proof.rs
- src/controller_examples/zookeeper_controller/proof/liveness/resource_match.rs
- src/kubernetes_cluster/proof/api_server_liveness.rs
- src/kubernetes_cluster/proof/controller_runtime_safety.rs
- src/kubernetes_cluster/proof/daemon_set_controller.rs
- src/kubernetes_cluster/proof/stateful_set_controller.rs
- src/kubernetes_cluster/spec/client/types.rs
- src/kubernetes_cluster/spec/cluster.rs
- src/kubernetes_cluster/spec/cluster_state_machine.rs
- src/kubernetes_cluster/spec/message.rs
- src/kubernetes_cluster/spec/mod.rs
- src/kubernetes_cluster/spec/pod_event/mod.rs
- src/kubernetes_cluster/spec/pod_event/state_machine.rs
- src/kubernetes_cluster/spec/pod_event/types.rs
I add a state machine to the cluster called `PodEvent` which issues random pod create, delete, and update requests on pods, while it is enabled. I also model a transition which disables `PodEvent`.
However, as implemented, not only are the liveness proofs of the controllers broken (that is to be expected), but also some of the proofs involving the builtin controllers in the compound state machine. For example, https://github.com/anvil-verifier/anvil/blob/3d0e043c1227c31213d9d07c050e1de32db8b387/src/kubernetes_cluster/proof/daemon_set_controller.rs#L298C10-L298C89 does not go through. Similar proofs are marked with a comment.
> Add PodEvent state machine to model random pod API requests

- src/controller_examples/v_replica_set_controller/proof/helper_invariants/proof.rs
- src/controller_examples/v_replica_set_controller/proof/liveness/spec.rs
- src/kubernetes_cluster/proof/cluster.rs
This PR adds the proof of the invariant in `no_pending_update_or_update_status_request_on_pods` (https://github.com/anvil-verifier/anvil/blob/main/src/controller_examples/v_replica_set_controller/proof/helper_invariants/predicate.rs), stating nothing in the cluster updates or updates the status of a pod. 
This is a provisional invariant: composition may require making this invariant less strict.
> Prove that there are no pending update or update status requests on pods

- src/v2/kubernetes_cluster/proof/mod.rs
- src/v2/kubernetes_cluster/proof/retentive_cluster.rs
- src/v2/kubernetes_cluster/spec/mod.rs
- src/v2/kubernetes_cluster/spec/retentive_cluster.rs
This PR augments the cluster state machine with a history that records all the past global state of the cluster. The history will help us prove some invariants that involve resource version of state objects.
Instead of modifying the cluster state machine's definition (and all its references) to maintain the history, this PR adds a new state machine, called retentive cluster, that wraps up the original state machine's `init` and `next` and meanwhile maintains a history of the original state machine. This brings several benefits: (1) it minimizes the changes we need to make to the current spec and lemmas (in fact, no changes are needed) to use the history variable, (2) it allows us to stick with the original state machine (w/o the history) in the cases where we don't need to use the history …
> Add history variable to the cluster state machine

- src/controller_examples/v_replica_set_controller/exec/reconciler.rs
- src/controller_examples/v_replica_set_controller/model/reconciler.rs
- src/kubernetes_api_objects/exec/api_method.rs
- src/kubernetes_api_objects/exec/mod.rs
- src/kubernetes_api_objects/exec/preconditions.rs
- src/kubernetes_api_objects/exec/prelude.rs
- src/kubernetes_api_objects/spec/api_method.rs
- src/kubernetes_api_objects/spec/mod.rs
- src/kubernetes_api_objects/spec/preconditions.rs
- src/kubernetes_api_objects/spec/prelude.rs
- src/kubernetes_cluster/proof/builtin_controllers.rs
- src/kubernetes_cluster/spec/builtin_controllers/garbage_collector.rs
- src/kubernetes_cluster/spec/client/state_machine.rs
- src/kubernetes_cluster/spec/message.rs
- src/kubernetes_cluster/spec/pod_event/state_machine.rs
- src/shim_layer/controller_runtime.rs
- src/unit_tests/kubernetes_api_objects/api_method.rs
- src/v2/controllers/vreplicaset_controller/exec/reconciler.rs
- src/v2/controllers/vreplicaset_controller/model/reconciler.rs
- src/v2/kubernetes_cluster/proof/garbage_collector.rs
- src/v2/kubernetes_cluster/proof/objects_in_store.rs
- src/v2/kubernetes_cluster/spec/api_server/state_machine.rs
- src/v2/kubernetes_cluster/spec/builtin_controllers/garbage_collector.rs
- src/v2/kubernetes_cluster/spec/message.rs
- src/v2/kubernetes_cluster/spec/pod_monkey/state_machine.rs
- src/vstd_ext/mod.rs
- src/vstd_ext/option_lib.rs
This PR introduces `preconditions` of Kubernetes delete requests. The `preconditions` contain a uid and a resource version. When handling the delete request, the API server checks whether the object's uid and resource version match the ones provided by the request and returns `Conflict` error if not. Kubernetes implements this feature here: https://github.com/kubernetes/kubernetes/blob/v1.30.0/staging/src/k8s.io/apiserver/pkg/storage/interfaces.go#L140-L153. The `preconditions` is optional. Introducing `preconditions` mainly requires changes to the API server model (modeling the uid and resource version checking) and the shim layer (passing the `preconditions` to `kube`).
This PR also fixes some of the lemmas that are broken due to `preconditions`.
Having `preconditions` allows us to use …
> Support `preconditions` for Delete request

- src/temporal_logic/rules.rs
This change allows `invariant_n!` to take only four parameters. It does not modify `invariant_n!` itself but modifies two other macros that `invariant_n!` depends on. This addresses #536 .
> Generalize `invariant_n!` to take only four parameters

- src/controller_examples/v_replica_set_controller/proof/helper_invariants/predicate.rs
- src/controller_examples/v_replica_set_controller/proof/helper_invariants/proof.rs
- src/controller_examples/v_replica_set_controller/proof/liveness/api_actions.rs
- src/controller_examples/v_replica_set_controller/proof/liveness/resource_match.rs
- src/controller_examples/v_replica_set_controller/proof/liveness/spec.rs
- src/controller_examples/v_replica_set_controller/proof/mod.rs
- src/controller_examples/v_replica_set_controller/proof/utility_lemmas.rs
- src/controller_examples/v_replica_set_controller/trusted/liveness_theorem.rs
- src/kubernetes_cluster/proof/cluster_safety.rs
The following invariants have been proven:
`every_create_matching_pod_request_implies_at_after_create_pod_step`
`every_delete_matching_pod_request_implies_at_after_delete_pod_step` (partially).
Investigating the latter led to addition of delete preconditions to the V2 state machine to which the controller will be ported.
> Prove key invariants for VReplicaSet possibly involving PodEvent

- src/v2/controllers/vreplicaset_controller/exec/reconciler.rs
- src/v2/controllers/vreplicaset_controller/model/reconciler.rs
- src/v2/controllers/vreplicaset_controller/trusted/liveness_theorem.rs
Here I've added the precondition on resource versions to delete requests sent by the model (and the exec) state machines. The conformance proof still goes through.
> Add delete precondition to V2 state machine for Verified ReplicaSet

- src/v2/controllers/vreplicaset_controller/exec/reconciler.rs
- src/v2/controllers/vreplicaset_controller/model/install.rs
- src/v2/controllers/vreplicaset_controller/model/reconciler.rs
- src/v2/controllers/vreplicaset_controller/trusted/exec_types.rs
- src/v2/controllers/vreplicaset_controller/trusted/spec_types.rs
- src/v2/kubernetes_cluster/proof/objects_in_store.rs
- src/v2/kubernetes_cluster/spec/install_helpers.rs
- src/v2/reconciler/exec/io.rs
- src/v2/reconciler/exec/reconciler.rs
- src/v2/reconciler/spec/io.rs
- src/v2/reconciler/spec/reconciler.rs
- src/v2_vreplicaset_controller.rs
This PR adds a helper function `installed_reconcile_model` that allows developers to easily install their reconciler into the v2 cluster state machine.
This PR also introduces some cosmetic changes including:
- simplifying the `Reconciler` trait to make it no longer depend on the `ExternalAPI` trait
- defining `VoidEReq` and `VoidEResp` in the `reconciler` mod for the controllers that do not depend on external systems
- moving some definitions out of `trusted`
The current shim layer cannot work with the new `Reconciler` trait. We will add a new compatible shim layer.
> Add helper function for installing reconcile model

- src/v2/kubernetes_cluster/proof/controller_runtime_safety.rs
- src/v2/kubernetes_cluster/spec/api_server/state_machine.rs
- src/v2/kubernetes_cluster/spec/api_server/types.rs
This PR also removes the `stable_resources` field and fixes a proof broken due to the removal (unpredictability of SMT solver again!).
> Document design choices behind the API server model

- src/v2/kubernetes_cluster/spec/cluster.rs
By removing the precondition on the API error type from `drop_req`, we generalize our fault model by including a new type of error: creation request with `generate_name` fails to create the object when all the creation attempts conflict with existing objects. This type of error is non-deterministic because the API server uses a name randomly generated when handling a creation request whose `name` is empty and `generate_name` is in use. We treat it as a transient error and assume that it will eventually disappear. Otherwise, there is no way for controllers that issue creation requests with `generate_name` to finish reconciliation.
> Model errors of create with `generate_name`

- src/vstd_ext/map_lib.rs
- src/vstd_ext/seq_lib.rs
- src/vstd_ext/set_lib.rs
Proved lemmas:
- `a_submap_of_a_finite_map_is_finite`
- `seq_pred_false_on_all_elements_is_equivalent_to_empty_filter`
- `finite_set_to_seq_contains_all_set_elements`
- `seq_filter_is_a_subset_of_original_seq`
- `seq_filter_contains_implies_seq_contains`
- `seq_filter_preserves_no_duplicates`
- `finite_set_to_seq_has_no_duplicates`
This PR reworked those in #578
I'll continue to work on this branch if any new lemma is added and create PR for more proofs
> Additional vstd lemmas proved

- src/v2/controllers/vreplicaset_controller/proof/liveness/mod.rs
- src/v2/controllers/vreplicaset_controller/proof/liveness/terminate.rs
- src/v2/controllers/vreplicaset_controller/proof/predicate.rs
Here, I port the termination proof for `VReplicaSet` to V2, as well as add universal quantification over ReplicaSets to this termination proof.
> Port Termination Proof to V2 for all VReplicaSets

- src/v2/controllers/vreplicaset_controller/proof/liveness/resource_match.rs
These are some proofs about VReplicaSet which rely on leads-to transitivity, mostly adapted from the V1 state machine version, except for some extra proof text.
> Prove leads-to chains in `resource_match.rs`

- src/v2/controllers/vreplicaset_controller/proof/liveness/resource_match.rs
- src/v2/kubernetes_cluster/spec/cluster.rs
- src/v2/kubernetes_cluster/spec/controller/state_machine.rs
- src/v2/kubernetes_cluster/spec/controller/types.rs
This introduces a `reconcile_id` field for each `OngoingReconcile` for a controller. When a reconcile is started, the allocator is queried for a new `reconcile_id`, and then is incremented. The `reconcile_id_allocator` is unique to each controller installed in the cluster, but is preserved across controller restarts for easier reasoning.
This addition slows down the proof for `lemma_from_after_send_create_pod_req_to_receive_ok_resp`, where I had to increase `rlimit`.
This is in service of a proof for the lemma proposed in https://github.com/anvil-verifier/anvil/pull/580 .
> Add a reconcile_id to each ongoing reconcile

- src/v2/kubernetes_cluster/proof/controller_runtime_safety.rs
- src/v2/kubernetes_cluster/spec/cluster.rs
Here some properties of the recently-introduced `reconcile_id` are proved. Recall that these are parameterized per `controller_id`, or per controller installed.
- If the `reconcile_id_allocator` is at a certain state, all started reconciles after that point have a greater `reconcile_id`.
- All ongoing reconciles have a `reconcile_id` less than the corresponding allocator.
- All ongoing reconciles have different `reconcile_id` fields.
> Prove some basic lemmas about reconcile_id

- src/temporal_logic/rules.rs
- src/v2/kubernetes_cluster/proof/controller_runtime_liveness.rs
- src/v2/kubernetes_cluster/proof/controller_runtime_safety.rs
- src/v2/kubernetes_cluster/proof/stability.rs
This lemma shows that if the spec ensures every newly started reconcile for a given controller_id satisfies some requirements (including termination of reconciles), the system will eventually reaches a state where all ongoing reconciles of that controller_id satisfy those requirements.
> Add new lemma stating all reconciles will eventually satisfy a set of requirements

- .github/workflows/ci.yml
- docker/controller/Dockerfile
- Fixed broken CI caused by rust toolchain update
- Added cache support for Verus build
- As we checked out the commit ID the cache will always be reused, so we could save 3mins for every jobs in CI
- Bumped Github action API call version and runner OS version
- Cache for Go environment is enabled by default since V4
However, as action cache does not support caching on relative path (we put Verus in `../verus` before), and there is no convenient way to get runner root dir instead of project root dir. There are 2 ways to workaround:
1. Export runner root dir in action runtime to action env, cache `${{env.runer_root}}/verus`, and reuse in each cache fetch
2. Just put verus in project root, which expands to `anvil/verus`. Require some runtime modification on CI jobs, together with runtime …
> Fix broken CI, add cache support for Verus build result, update CI OS

- .github/workflows/ci.yml
- deploy.sh
- deploy/v2_vreplicaset/crd.yaml
- deploy/v2_vreplicaset/deploy_local.yaml
- deploy/v2_vreplicaset/deploy_remote.yaml
- deploy/v2_vreplicaset/rbac.yaml
- deploy/v2_vreplicaset/v2_vreplicaset.yaml
- e2e/src/main.rs
- e2e/src/v2_vreplicaset_e2e.rs
- local-test.sh
These tests duplicate the functionality of the V1 tests as of now. Note that I have also adapted some scripts to convert between `snake_case`, as used in filenames, and `kebab-case`, as used in the .yaml files (see `v2_vr..` versus `v2-vr..`).
> Add e2e tests for V2 VReplicaSet

- src/v2/controllers/vreplicaset_controller/proof/helper_invariants/predicate.rs
- src/v2/controllers/vreplicaset_controller/proof/helper_invariants/proof.rs
- src/v2/controllers/vreplicaset_controller/proof/liveness/api_actions.rs
- src/v2/controllers/vreplicaset_controller/proof/liveness/resource_match.rs
- src/v2/controllers/vreplicaset_controller/trusted/liveness_theorem.rs
Here I specify the rely condition for VReplicaSet: no controller creates/updates/deletes pods that are owned by a VReplicaSet.
I don't yet know how many proofs this breaks: once I have an idea (by running and marking the appropriate proofs), I will document this in the PR.
> Specification of Rely-Condition for VReplicaSet

- src/v2/controllers/vreplicaset_controller/proof/helper_invariants/proof.rs
- src/v2/controllers/vreplicaset_controller/proof/liveness/api_actions.rs
- src/v2/controllers/vreplicaset_controller/proof/liveness/resource_match.rs
- src/v2/controllers/vreplicaset_controller/trusted/liveness_theorem.rs
I also make a few changes to the rely-condition:
- For the Create portion, it actually suffices to just ensure that the object in the create message isn't controller-owned by any VRS.
- For the Update and UpdateStatus portions, we require that those requests carry a resource version. We need this because the current state machine model actually allows unconditional updates on `Pods` (but disallows this for CustomResources).
> Repair all proofs broken by VRS Non-Interference Rely Condition

- src/v2/controllers/vreplicaset_controller/trusted/liveness_theorem.rs
- src/v2/kubernetes_cluster/spec/api_server/state_machine.rs
- src/vstd_ext/map_lib.rs
This PR simply inlines `map_to_seq` in the spec of API server's list handler and removes the definition of `map_to_seq`.
> Flatten spec of API server's list handler

- src/v2/controllers/vreplicaset_controller/proof/helper_lemmas.rs
- src/v2/controllers/vreplicaset_controller/proof/liveness/proof.rs
- src/v2/controllers/vreplicaset_controller/proof/liveness/resource_match.rs
- src/v2/controllers/vreplicaset_controller/proof/predicate.rs
- src/v2/controllers/vreplicaset_controller/trusted/liveness_theorem.rs
- src/v2/kubernetes_cluster/proof/req_resp.rs
I restate the ESR property as filtering `s.resources().values()` as suggested in the comments of one of the files. 
Note that we define the pods matching a replicaset by filtering `s.resources().values()` using the function `matching_pods`. My intention is to have this function replace `matching_pod_keys` (what used to be called `matching_pods`), which gives a set of _keys_ of matching pods, and `matching_pod_entries`, which provides a _submap_ of keys to matching pods.
> Restate ESR property for VRS; breaks proofs

- src/v2/controllers/vdeployment_controller/trusted/exec_types.rs
- src/v2/controllers/vdeployment_controller/trusted/spec_types.rs
- src/vstd_ext/string_view.rs
- Use macros to reduce LOC in CR
- Move `string_equal` to vstd_ext::string_view
> Use macro to define VDeployment

- src/v2/controllers/vreplicaset_controller/proof/helper_invariants/predicate.rs
- src/v2/controllers/vreplicaset_controller/proof/helper_invariants/proof.rs
- src/v2/controllers/vreplicaset_controller/proof/helper_lemmas.rs
- src/v2/controllers/vreplicaset_controller/proof/liveness/api_actions.rs
- src/v2/controllers/vreplicaset_controller/proof/liveness/proof.rs
- src/v2/controllers/vreplicaset_controller/proof/liveness/resource_match.rs
- src/v2/controllers/vreplicaset_controller/proof/predicate.rs
- src/v2/controllers/vreplicaset_controller/trusted/liveness_theorem.rs
- src/v2/kubernetes_cluster/proof/controller_runtime_safety.rs
- src/v2/kubernetes_cluster/proof/req_resp.rs
Here, I change the ESR definition for `VReplicaSet` as well as some associated definitions. I fix most of the proofs that are broken by these changes, except for ones that would require a different kind of argument (such arguments relied heavily on maps from `ObjectRef` to `DynamicObjectView`, but `matching_pods` is redefined in terms of filtered sets of objects).
I'd like to call attention to a flaky proof `lemma_always_cr_objects_in_etcd_satisfy_state_validation` which increases the total verification time for VRS from ~2m real time on my machine to ~6m.
> Change ESR definition; fix most proofs

- src/v2/controllers/vreplicaset_controller/proof/helper_invariants/proof.rs
- src/v2/kubernetes_cluster/proof/controller_runtime_safety.rs
Here I reduce the total verification time of `./build.sh v2_vreplicaset_controller.rs` from 6 minutes to 3 minutes on my machine. The flakiness of these proofs is still something we need to address, but it's less urgent.
> Mitigate the impact of flaky proofs

- src/v2/controllers/vreplicaset_controller/proof/helper_invariants/predicate.rs
- src/v2/kubernetes_cluster/proof/objects_in_store.rs
Here I specify a boundary invariant which states that any message sent not by the reconcile associated with the particular `vrs` we prove ESR for will not interfere with that reconcile process.
The body of the invariant is inspired by https://github.com/anvil-verifier/anvil/pull/630
> Specify simplified boundary invariant between invariant and WF1 reasoning

- src/v2/kubernetes_cluster/spec/cluster.rs
This fixes an off-by-one error in `controller_action_pre`: instead of forcing the `ObjectRef` to be non-null, it forces the message to be `null`, whereas it is allowed that a controller takes a step without a message as input.
This is separate from the rest of subtask in (https://github.com/xlab-uiuc/anvil/issues/26) since spec/trusted code is modified.
> Fix off-by-one error in controller action precondition

- src/v2/controllers/vdeployment_controller/proof/liveness/terminate.rs
- src/v2/controllers/vdeployment_controller/proof/predicate.rs
- src/v2/controllers/vdeployment_controller/trusted/step.rs
Follow up of https://github.com/anvil-verifier/anvil/pull/644
Managed to use macro instead of trait, made several compromising:
- Use dummy trigger
- Use wrapper of macro as trigger
- Use trigger at inner layer
- But again it works and proof isn't slow
> Use macro for VD termination proof

- src/v2/controllers/vreplicaset_controller/proof/helper_invariants/predicate.rs
- src/v2/controllers/vreplicaset_controller/proof/helper_invariants/proof.rs
- src/v2/controllers/vreplicaset_controller/proof/helper_lemmas.rs
- src/v2/controllers/vreplicaset_controller/proof/liveness/api_actions.rs
- src/v2/controllers/vreplicaset_controller/proof/liveness/proof.rs
- src/v2/controllers/vreplicaset_controller/proof/liveness/resource_match.rs
- src/v2/controllers/vreplicaset_controller/proof/liveness/spec.rs
- src/v2/controllers/vreplicaset_controller/proof/predicate.rs
- src/v2/kubernetes_cluster/proof/controller_runtime_safety.rs
This PR rewrites the liveness proof to use a bridge invariant saying that no message potentially interfering with the current reconcile for `vrs` can be in the network, unless the source is precisely the reconcile for `vrs`. The fixes are complete minus a helper lemma, and lemmas specifying the results of the API server taking an action.
> Fix WF1 proofs on 'top' (liveness) side of Bridge Invariant

- src/v2/controllers/vdeployment_controller/exec/reconciler.rs
- src/v2/controllers/vdeployment_controller/model/reconciler.rs
- src/v2/controllers/vdeployment_controller/trusted/liveness_theorem.rs
- src/v2/controllers/vdeployment_controller/trusted/util.rs
Fix a bug when there are multiple VReplicaset matching VDeployment's template, VDeployment controller can not reconcile the cluster state to be desired state by scaling down all but one of them.
Previously the check on managed ReplicaSets was
```rust
if new_vrs_list.len() == 0 {
// create the new vrs
create_new_vrs(state, vd)
} else {
let new_vrs = new_vrs_list.last();
let state = VDeploymentReconcileState {
new_vrs: Some(new_vrs),
..state
};
// ..
```
Because when replicating the logic of k8s ReplicaSet(RS) controller, there was one [comment](https://github.com/kubernetes/kubernetes/blob/73014647f9bdd7186b5fe121326b961d6521c162/pkg/controller/deployment/util/deployment_util.go#L633-L636):
```rust
// In rare cases, such as after cluster upgrades, Deployment may end up with 
// having more …
```
> Fix VDeployment reconciler bug

- src/controllers/vdeployment_controller/exec/reconciler.rs
- src/controllers/vdeployment_controller/model/reconciler.rs
- src/controllers/vdeployment_controller/proof/liveness/terminate.rs
- src/controllers/vdeployment_controller/trusted/step.rs
- src/controllers/vdeployment_controller/trusted/util.rs
- Add barrier state of `AfterEnsureNewVRS`
- Add wrappers back as the flakiness is resolved
- remove deprecated `#[is_variant]`
> Add AfterEnsureNewVRS to VD States

- src/controllers/vdeployment_controller/exec/reconciler.rs
- src/controllers/vdeployment_controller/model/reconciler.rs
As discovered by @codyjrivera at `AfterListVRS` step the previous state doesn't have `new_vrs` and `old_vrs_list` available, and I forgot to update these 2 fields using information in list response.
This PR fixes the bug.
> Fix VDeployment controller bug: Fields are not updates at `AfterListVRS` step

- src/controllers/vdeployment_controller/proof/liveness/terminate.rs
- src/temporal_logic/rules.rs
Remove all usage of `tla_exists_proved_by_witness` and make it private.
After #662 is merged this can be rebased and merged to main.
> Make `tla_exists_proved_by_witness` private

- src/controllers/vdeployment_controller/proof/liveness/api_actions.rs
- src/controllers/vdeployment_controller/proof/liveness/resource_match.rs
- src/controllers/vdeployment_controller/proof/liveness/terminate.rs
- src/controllers/vdeployment_controller/proof/predicate.rs
- src/controllers/vdeployment_controller/trusted/liveness_theorem.rs
- src/controllers/vreplicaset_controller/pub_mod.rs
- src/temporal_logic/rules.rs
- Patch ESR to use predicates on etcd state
- Complete WF1 top level proof for VDeployment controller
- mask broken transition lemmas for future PR
Minor change:
- unify `dummy` trigger for easier usage
- as `vreplicaset_controller::trusted` is the only module required by VDeployment controller, update the `pub_mod.rs`
> WF1 proof for VDeployment controller

- src/controllers/vdeployment_controller/proof/guarantee.rs
- src/controllers/vdeployment_controller/proof/helper_invariants/predicate.rs
- src/controllers/vdeployment_controller/proof/helper_invariants/proof.rs
- src/controllers/vdeployment_controller/proof/helper_lemmas.rs
- src/controllers/vdeployment_controller/proof/predicate.rs
- src/controllers/vdeployment_controller/trusted/rely_guarantee.rs
- src/kubernetes_cluster/proof/objects_in_store.rs
Here I prove some additional invariants, including the boundary lemma `lemma_eventually_always_no_other_pending_request_interferes_with_vd_reconcile`. An invariant stating the garbage collector won't interfere with reconciliation remains unproven; this reasoning is complicated by the `GetThenUpdate` request that the `VDeployment` controller sends.
> Prove more VD invariants

- src/controllers/vdeployment_controller/exec/reconciler.rs
- src/controllers/vdeployment_controller/trusted/spec_types.rs
- src/controllers/vreplicaset_controller/trusted/spec_types.rs
- src/kubernetes_api_objects/exec/label_selector.rs
- src/kubernetes_api_objects/exec/object_meta.rs
- src/kubernetes_api_objects/spec/object_meta.rs
Add finite requirement `.metadata.labels` and `.spec.selector.match_labels` for VDeployment and VReplicaSet CRs
> Add requirements that `map` and `seq` should be finite

- src/vstd_ext/seq_lib.rs
Add a seq lemma of `map_values_weakens_no_duplicates`: `s.map_values().no_duplicates() -> s.no_duplicates()`
> Prove `map_values_weakens_no_duplicates`

- src/controllers/vdeployment_controller/exec/reconciler.rs
- src/controllers/vdeployment_controller/model/reconciler.rs
- src/controllers/vdeployment_controller/proof/liveness/resource_match.rs
- src/controllers/vdeployment_controller/proof/liveness/terminate.rs
- src/controllers/vdeployment_controller/proof/predicate.rs
This PR updates VDeployment controller reconciler to use old_vrs_index to record current progress just as VRS controller does
> Use old_vrs_index to record current progress, keep all old vrs in cache

- src/controllers/vdeployment_controller/proof/helper_invariants/predicate.rs
- src/controllers/vdeployment_controller/proof/helper_invariants/proof.rs
- src/controllers/vdeployment_controller/proof/helper_lemmas.rs
- src/controllers/vdeployment_controller/proof/predicate.rs
- src/kubernetes_cluster/proof/controller_runtime_safety.rs
Prove that the Kubernetes garbage collector does not delete ReplicaSets associated with the Deployment controller we want reconciled.
> Prove Garbage Collection Invariants

- src/controllers/vdeployment_controller/proof/helper_invariants/proof.rs
- src/controllers/vdeployment_controller/proof/liveness/proof.rs
- src/controllers/vdeployment_controller/proof/liveness/spec.rs
- src/controllers/vdeployment_controller/proof/liveness/terminate.rs
This pull request weaves the invariants written and proved in earlier PRs into the top-level proof structure.
It also generalizes Cathy's termination argument to apply to an arbitrary `VDeployment` controller.
> Insert invariants into top-level proof

- src/controllers/vreplicaset_controller/proof/liveness/resource_match.rs
This is a quick fix that shuffles around some intermediate asserts to correct the proof. The fix allows the proof in the branch `xudong/composition` to go through, though of course the PR is merging on `main`. If a more systematic investigation should be performed, please ping me.
> Stopgap fix for lemma_from_after_receive_list_pods_resp_to_send_delete_pod_req

- src/controllers/vdeployment_controller/proof/liveness/api_actions.rs
Prove `lemma_api_request_other_than_pending_req_msg_maintains_objects_owned_by_vd`. This lemma picks out the proof at https://github.com/anvil-verifier/anvil/blob/e5d5c53b8c7330183d2014370a849de4a355bcc3/src/controllers/vdeployment_controller/proof/liveness/resource_match.rs#L1517-L1596
And is helpful to prove other API action lemmas
> Prove lemma_api_request_other_than_pending_req_msg_maintains_objects_owned_by_vd

- .github/workflows/ci.yml
- src/controllers/vdeployment_controller/mod.rs
- src/controllers/vreplicaset_controller/mod.rs
- src/controllers/vstatefulset_controller/mod.rs
This PR modifies the CI script so that when verifying each controller, it no longer checks Anvil's built-in lemmas.
This PR adds a trivial proof `proof fn trivial() ensures true {}` to the `mod.rs` of each controller module because of a bug in the `--verify-module` according to Travis "the way it [`--verify-module`] works is it collects a list of modules based on which modules have a nonzero number of verification conditions"
> Avoid verifying Anvil built-in lemmas repeatedly

- src/controllers/vdeployment_controller/proof/liveness/api_actions.rs
- src/controllers/vdeployment_controller/proof/liveness/resource_match.rs
- src/controllers/vdeployment_controller/proof/predicate.rs
- Prove **all** transition lemmas in `src/controllers/vdeployment_controller/proof/liveness/resource_match.rs`
- Fix multiple bugs in `src/controllers/vdeployment_controller/proof/predicate.rs`
- Move `local_state_is_valid_and_coherent` to post-conditions of `lemma_api_request_other_than_pending_req_msg_maintains_local_state_coherence` to make it more general
> Prove VDeployment controller transition lemmas

- src/controllers/vdeployment_controller/proof/liveness/resource_match.rs
- src/controllers/vdeployment_controller/proof/predicate.rs
- src/controllers/vdeployment_controller/trusted/liveness_theorem.rs
- Removed unused `resp_objs == s.resources().values().filter(list_vrs_obj_filter(vd.metadata.namespace)).to_seq()` from `resp_msg_is_ok_list_resp_containing_matched_vrs`
- It turned out to be an unnecessary requirement added to ESR, removed altogether
```rust
let objs = s.resources().values().filter(list_vrs_obj_filter(vd.metadata.namespace)).to_seq();
objects_to_vrs_list(objs) is Some
```
- Add comments explaining ownership of VRS by VD controller
> Fix bug in `resp_msg_is_ok_list_resp_containing_matched_vrs`

- src/controllers/vdeployment_controller/proof/liveness/resource_match.rs
- src/controllers/vdeployment_controller/proof/predicate.rs
This is a simpler workaround compared to weaken `vd.well_formed` requirement for utility functions or adapt `generate_name`
> Weaken at_vd_step_with_vd to not talk about vd RV
