anvil-verifier/anvil

- src/kubernetes_cluster/proof/controller_runtime_safety.rs
- src/kubernetes_cluster/proof/kubernetes_api_liveness.rs
- src/kubernetes_cluster/proof/kubernetes_api_safety.rs
- src/kubernetes_cluster/spec/client.rs
- src/kubernetes_cluster/spec/common.rs
- src/kubernetes_cluster/spec/controller/controller_runtime.rs
- src/kubernetes_cluster/spec/kubernetes_api/builtin_controllers/statefulset_controller.rs
- src/kubernetes_cluster/spec/kubernetes_api/state_machine.rs
- src/simple_controller/proof/liveness.rs
- src/simple_controller/proof/shared.rs
- src/simple_controller/spec/simple_reconciler.rs
Cosmetic changes to simplify specs on sending/receiving messages.
> Cosmetic changes to clean up message related methods in spec

- src/simple_controller/mod.rs
- src/simple_controller/proof/liveness.rs
- src/simple_controller/proof/mod.rs
- src/simple_controller/proof/safety.rs
- src/simple_controller/proof/shared.rs
- src/simple_controller/spec/simple_reconciler.rs
Fix the safety and part of the liveness proof of the simple controller.
> WIP: Fix simple controller proof

- src/simple_controller/proof/liveness.rs
Prove the lemma `lemma_after_get_cr_pc_leads_to_cm_always_exists` in module `simple_controller::proof::liveness`. This lemma ensures that for every valid execution, the state where the reconciler gets a custom resource and the pc equals `after_get_cr_pc()` always implies kubernetes api will eventually always contain the same custom resource.
> Fix liveness proof: `after_get_cr_pc ~> cm_always_exists`

- src/controller_examples/simple_controller/spec/custom_resource.rs
- src/controller_examples/simple_controller/spec/reconciler.rs
- src/kubernetes_api_objects/config_map.rs
- src/kubernetes_api_objects/persistent_volume_claim.rs
- src/kubernetes_api_objects/pod.rs
- src/kubernetes_api_objects/resource.rs
- src/kubernetes_api_objects/service.rs
- src/kubernetes_api_objects/stateful_set.rs
Also comment out the fields that are currently not used in our exec and spec.
> Implement ResourceView for each Kubernetes object type

- deploy/simple/deploy.yaml
- docker/simple_controller_build/Dockerfile
- reference_controllers/simple_controller/src/main.rs
- reference_controllers/zookeeper_controller/src/main.rs
- src/shim_layer/mod.rs
- src/simple_controller.rs
The option controls whether to export the CRD in yaml or run the reconciliation loops.
> Add an option to the simple controller

- .github/workflows/controller-image-build.yml
- deploy.sh
- deploy/rabbitmq/crd.yaml
- deploy/rabbitmq/deploy.yaml
- deploy/rabbitmq/rabbitmq.yaml
- docker/rabbitmq-controller/Dockerfile
- reference-controllers/rabbitmq-controller/src/statefulset.rs
Build the rabbitmq controller image to facilitate future testing.
> Prepare to deploy rabbitmq controller

- src/controller_examples/zookeeper_controller/proof/liveness.rs
This lemma states that from any state, it leads to a state where from now it is always true that if the controller is reconciling for an object whose key is `zk.object_ref()`, that object's spec is the same as `zk.spec`. This lemma requires that in the spec we have `[] desired_state_is(zk)`.
The proof is not very straightforward, we need to apply the unpack rule and another lemma `lemma_true_leads_to_always_the_object_in_schedule_has_spec_as`.
> Prove lemma_true_leads_to_always_the_object_in_reconcile_has_spec_as

- src/kubernetes_cluster/spec/kubernetes_api/state_machine.rs
Separate out validation logic for creating and updating requests from their handling logic. This also helps to avoid the copy-paste errors such as the one fixed by https://github.com/vmware-research/verifiable-controllers/commit/9ec7fb469c4d0d3e7e3e6395d04488a081383823.
> Separate out request validation logic

- reference-controllers/zookeeper-controller/Cargo.lock
- reference-controllers/zookeeper-controller/Cargo.toml
- reference-controllers/zookeeper-controller/src/main.rs
Support modifying zookeeper membership list in a declarative way.
> Support modifying membership list in unverified zookeeper controller

- src/kubernetes_api_objects/cluster_role.rs
- src/kubernetes_api_objects/cluster_role_binding.rs
- src/kubernetes_api_objects/common.rs
- src/kubernetes_api_objects/daemon_set.rs
- src/kubernetes_api_objects/mod.rs
These data types will be used to build the verified fluent controller.
> Implement daemon set, cluster role and cluster role binding wrappers and views

- src/kubernetes_cluster/proof/kubernetes_api_liveness.rs
- src/kubernetes_cluster/proof/message.rs
- src/temporal_logic/rules.rs
Simplified a few lemmas to demonstrate its usage.
> Simplify strengthening next using `strengthen_next_n!(...)`

- src/controller_examples/rabbitmq_controller/proof/common.rs
- src/controller_examples/zookeeper_controller/proof/liveness/helper_invariants.rs
- src/kubernetes_cluster/proof/controller_runtime_safety.rs
- src/kubernetes_cluster/proof/kubernetes_api_liveness.rs
- src/kubernetes_cluster/proof/message.rs
- src/kubernetes_cluster/spec/client/state_machine.rs
- src/kubernetes_cluster/spec/client/types.rs
- src/kubernetes_cluster/spec/cluster_state_machine.rs
We don't need wf assumptions for the client state machine, so we should just let the client state machine to choose the input (from its step).
> Let the client state machine choose the input

- src/kubernetes_api_objects/container.rs
- src/kubernetes_api_objects/object_meta.rs
- src/kubernetes_api_objects/resource_requirements.rs
- src/kubernetes_api_objects/stateful_set.rs
- src/unit_tests/kubernetes_api_objects/config_map.rs
- src/unit_tests/kubernetes_api_objects/container.rs
- src/unit_tests/kubernetes_api_objects/lifecycle.rs
- src/unit_tests/kubernetes_api_objects/mod.rs
- src/unit_tests/kubernetes_api_objects/object_meta.rs
- src/unit_tests/kubernetes_api_objects/probe.rs
- src/unit_tests/kubernetes_api_objects/resource_requirements.rs
Copied the same tests from #278 with a clean git history.
> Add unit tests for Container and ConfigMap

- deploy/fluent/crd.yaml
- src/controller_examples/fluent_controller/fluentbit/exec/resource/daemon_set.rs
- src/controller_examples/fluent_controller/fluentbit/model/resource/daemon_set.rs
- src/controller_examples/fluent_controller/fluentbit/trusted/exec_types.rs
- src/controller_examples/fluent_controller/fluentbit/trusted/spec_types.rs
- src/deps_hack/src/lib.rs
Add `args`, `command`, `image_pull_policy`, `image_pull_secrets`, `env_vars`, `liveness_probe` and `readiness_probe`.
> Add fields to fluentbit spec

- .github/workflows/ci.yml
- src/kubernetes_api_objects/exec/container.rs
- src/kubernetes_api_objects/exec/service.rs
- src/kubernetes_api_objects/spec/container.rs
- src/kubernetes_api_objects/spec/service.rs
Add more fields, their setter and getter methods to `ServicePort` and `ContainerPort`.
> Add fields and methods to `ServicePort` and `ContainerPort`

- src/vstd_ext/mod.rs
- src/vstd_ext/vec_lib.rs
> Add verified filter for Vec

- .github/workflows/ae.yml
- docker/ae/Dockerfile
The built image is used for reproducing verification results for the artifact evaluation.
> Workflow for building AE image

- AE.md
Some to-dos:
- Update `anvil-ae-one-controller.sh` and `anvil-ae-sampled.sh` to take the sample rate as an argument
- Change the value of the `Controller` column of the generated Table 3 to `ZooKeeper`, `RabbitMQ` and `FluentBit` to keep consistent with the paper
- Handle the SSL exception (if easy to do)
> Update perf evaluation instructions

- src/temporal_logic/rules.rs
Remove some TLA proof rules that are redundant. Also, make some other proof rules private, as they don't need to be exposed to users.
> Remove redundant proof rules

- .github/workflows/ci.yml
- e2e/Cargo.lock
- e2e/Cargo.toml
- src/controller_examples/rabbitmq_controller/exec/resource/stateful_set.rs
- src/controller_examples/rabbitmq_controller/model/resource/stateful_set.rs
- src/controller_examples/zookeeper_controller/exec/resource/stateful_set.rs
- src/controller_examples/zookeeper_controller/model/resource/stateful_set.rs
- src/deps_hack/Cargo.lock
- src/deps_hack/Cargo.toml
- src/kubernetes_api_objects/exec/mod.rs
- src/kubernetes_api_objects/exec/persistent_volume_claim.rs
- src/kubernetes_api_objects/exec/volume_resource_requirements.rs
- src/kubernetes_api_objects/spec/mod.rs
- src/kubernetes_api_objects/spec/persistent_volume_claim.rs
- src/kubernetes_api_objects/spec/volume_resource_requirements.rs
- src/shim_layer/controller_runtime.rs
- src/unit_tests/kubernetes_api_objects/persistent_volume_claim.rs
- src/unit_tests/kubernetes_api_objects/persistent_volume_claim_spec.rs
* Upgrade `kube` to 0.91.0
* Upgrade `k8s-openapi` to 0.22.0
* Fix some discrepancies caused by upgrading
> Bump Kubernetes version to v1.30.0

- src/v2/controllers/vreplicaset_controller/proof/helper_invariants/mod.rs
- src/v2/controllers/vreplicaset_controller/proof/helper_invariants/predicate.rs
- src/v2/controllers/vreplicaset_controller/proof/helper_lemmas.rs
- src/v2/controllers/vreplicaset_controller/proof/liveness/api_actions.rs
- src/v2/controllers/vreplicaset_controller/proof/liveness/mod.rs
- src/v2/controllers/vreplicaset_controller/proof/liveness/resource_match.rs
- src/v2/controllers/vreplicaset_controller/proof/mod.rs
- src/v2/controllers/vreplicaset_controller/proof/predicate.rs
- src/v2/kubernetes_cluster/proof/failures_liveness.rs
- src/v2/kubernetes_cluster/proof/network.rs
In this pull request, I prove the WF1 lemmas related to the initialization phase of the ReplicaSet controller.
> VReplicaSet: Prove List WF1 Lemmas in State Machine Version 2

- src/v2/controllers/vreplicaset_controller/proof/helper_invariants/predicate.rs
- src/v2/controllers/vreplicaset_controller/proof/liveness/resource_match.rs
Prove delete WF1 lemmas for ReplicaSet in V2 state machine.
> Prove Delete Lemmas for ReplicaSet in V2 State Machine

- src/v2/controllers/vreplicaset_controller/proof/helper_invariants/mod.rs
- src/v2/controllers/vreplicaset_controller/proof/helper_invariants/predicate.rs
- src/v2/controllers/vreplicaset_controller/proof/helper_invariants/proof.rs
- src/v2/controllers/vreplicaset_controller/proof/helper_lemmas.rs
- src/v2/controllers/vreplicaset_controller/proof/liveness/api_actions.rs
- src/v2/controllers/vreplicaset_controller/proof/liveness/resource_match.rs
- src/v2/controllers/vreplicaset_controller/proof/predicate.rs
- src/v2/kubernetes_cluster/proof/controller_runtime_liveness.rs
- src/v2/kubernetes_cluster/proof/objects_in_store.rs
- src/vstd_ext/seq_lib.rs
Two major invariants: at the core of the add and delete loops, have been proved.
> Prove core invariants for ReplicaSet in V2 state machine

- .github/workflows/ci.yml
- .github/workflows/verus-build.yml
- README.md
- rust-toolchain.toml
- src/controller_examples/v_replica_set_controller/proof/liveness/resource_match.rs
- src/temporal_logic/defs.rs
- src/temporal_logic/rules.rs
- src/v2/controllers/vreplicaset_controller/proof/liveness/resource_match.rs
- update func_ext due to https://github.com/verus-lang/verus/commit/07258e9dc17cd02b7fb9b6f7395f46baa5c020b8
- update deps_hack to rust 1.82.0
- update CI
> Update to newest verus version

- src/v2/kubernetes_cluster/proof/objects_in_store.rs
Proved `lemma_always_each_object_in_etcd_has_at_most_one_controller_owner`
> lemma_always_each_object_in_etcd_has_at_most_one_controller_owner proved

- src/v2/kubernetes_cluster/proof/objects_in_store.rs
- simplified `lemma_always_each_object_in_etcd_has_at_most_one_controller_owner`
- simplified `lemma_always_etcd_is_finite`
> Simplify the proof of `lemma_always_each_object_in_etcd_has_at_most_one_controller_owner` and `lemma_always_etcd_is_finite`

- src/vstd_ext/map_lib.rs
- src/vstd_ext/seq_lib.rs
- src/vstd_ext/set_lib.rs
Proved following vstd lemma introduced in #587
- <s>`lemma_k_v`</s>
- `push_to_set_eq_to_set_insert`
- `map_values_to_set_eq_to_set_mk_map_values`
- `lemma_mk_map_insert_k`
> Prove vstd lemma of `push_to_set_eq_to_set_insert`, `map_values_to_set_eq_to_set_mk_map_values`, `lemma_mk_map_insert_k`, `lemma_k_v`

- .github/workflows/controller-build.yml
@marshtompsxd 
added a job to the controller-build workflow to build the admission control docker image as requested
> ci: add build-vreplicaset-admission-controller to controller build workflow

- build.md
- Delete mention of `admission_setup.sh`
- Make it briefer
> Fix outdated build.md

- src/kubernetes_api_objects/exec/api_method.rs
- src/v2/controllers/vdeployment_controller/exec/reconciler.rs
- src/v2/controllers/vdeployment_controller/model/reconciler.rs
- src/v2/reconciler/exec/io.rs
- src/v2/reconciler/spec/io.rs
- Update VDeployment Controller's API calls
- Add corresponding macros and methods for new transactional APIs
> Adopt transactional API for VDeployment controller

- src/kubernetes_api_objects/exec/object_meta.rs
- src/kubernetes_api_objects/spec/object_meta.rs
- src/v2/controllers/vdeployment_controller/exec/reconciler.rs
- src/v2/controllers/vdeployment_controller/trusted/exec_types.rs
- src/v2/controllers/vdeployment_controller/trusted/spec_types.rs
- src/v2/controllers/vreplicaset_controller/proof/helper_invariants/predicate.rs
- src/v2/controllers/vreplicaset_controller/proof/helper_invariants/proof.rs
- src/v2/controllers/vreplicaset_controller/trusted/exec_types.rs
- src/v2/controllers/vreplicaset_controller/trusted/spec_types.rs
- src/v2/controllers/vstatefulset_controller/trusted/spec_types.rs
- src/v2/kubernetes_cluster/proof/objects_in_reconcile.rs
- src/v2/kubernetes_cluster/proof/objects_in_store.rs
- src/v2/reconciler/exec/reconciler.rs
- Update `well_formed` to `well_formed_for_namespaced`
- Fix bug of namespace is checked in spec while not checked in exec
> Update `well_formed` to `well_formed_for_namespaced` and fix bug in exec

- src/kubernetes_api_objects/exec/api_method.rs
- src/kubernetes_api_objects/spec/api_method.rs
- src/v2/controllers/vdeployment_controller/trusted/mod.rs
- src/v2/controllers/vdeployment_controller/trusted/rely_guarantee.rs
- src/v2/shim_layer/controller_runtime.rs
- add reliance conditions for deployment controller
- add TODO for type invariants in transactional API
> Specify non interference rely/guarantee conditions of deployment controller

- src/controllers/vdeployment_controller/proof/guarantee.rs
- src/controllers/vdeployment_controller/proof/helper_invariants/predicate.rs
- src/controllers/vdeployment_controller/proof/helper_invariants/proof.rs
- src/controllers/vdeployment_controller/proof/mod.rs
- src/controllers/vdeployment_controller/trusted/rely_guarantee.rs
- src/controllers/vreplicaset_controller/proof/guarantee.rs
I provide proofs for a couple of invariants for VD whose bodies are basically identical to those in the VRS proof.
Proving the guarantee condition and proving the garbage collector won't interfere are major missing proofs.
> Prove 'low-hanging' VD helper invariants

- src/controllers/vdeployment_controller/proof/liveness/spec.rs
`tla_forall(|input| cluster.disable_crash().weak_fairness(input))` -> `cluster.disable_crash().weak_fairness(controller_id)`
> Weaken VD controller crash assumption
